# Retrieve all college urls from .html file

In [1]:
import requests
from bs4 import BeautifulSoup

list_colleges_url = []

url_base = 'https://www.usnews.com'

# This is the file you helped us create using Selenium // your VS code
college_ranking_file = open("CollegeRankings.html", "r", encoding="utf8")  
  
# Reading the file and storing in a variable 
contents = college_ranking_file.read() 
  
# Creating a BeautifulSoup object and  
# specifying the parser 
soup = BeautifulSoup(contents, 'html.parser')

url_location = soup.find_all("a", class_="Anchor-byh49a-0 Card__StyledAnchor-sc-1ra20i5-10 eMEqFO exfxTA card-name")

# Add each school's URL into a list that we can use for webscraping
for url in url_location:
    tag = url.get('href')
    list_colleges_url.append(url_base + tag)
    
print(list_colleges_url)

FileNotFoundError: [Errno 2] No such file or directory: 'CollegeRankings.html'

# Scrape college information from a specific .html file

In [2]:
import requests
from bs4 import BeautifulSoup

# THIS IS A TEST FOR ONE SCHOOL. IT DOES NOT UTILIZE THE FOR LOOP!!!!!

college_ranking_file = open("mhb.html", "r", encoding="utf8")  
  
# Reading the file and storing in a variable 
contents = college_ranking_file.read() 
  
# Creating a BeautifulSoup object and  
# specifying the parser 
soup = BeautifulSoup(contents, 'html.parser')


# Now we go through each class and do various edits such as replacing "$,#, spaces, commas"
name_full = soup.find('h1', class_='Heading-sc-1w5xk2o-0 Wakanda__Title-rzha8s-10 gTHiRT gtkLHO').text
print(name_full)

## remove "#" and split on spaces
    ## check if contains "-" and if so, split again on dash
    ## if not, keep the original split

ranking_text = soup.find('span', class_='Villain__RankingSpan-sc-8s66oj-4 fDSmVR').text
ranking = ranking_text.split(" ")[0].replace('#', "")
if "-" in ranking:
    ranking = ranking.split("-")[0]

print("Ranked: " + ranking)


text = soup.find_all('p', class_='Paragraph-sc-1iyax29-0 kqzCwD')

setting = text[0].text
tuition_and_fees = text[1].text.replace("$", "").replace(",", "")
undergraduate_enrollment = text[2].text.replace(",", "")
acceptance_rate = text[3].text.replace("%", "")

# Using indices we separated the SAT and ACT ranges
# sat_range = text[4]
sat_lower = text[4].text.split('-')[0]
sat_upper = text[4].text.split('-')[1]

# act_range = text[5].text
act_lower = text[5].text.split('-')[0]
act_upper = text[5].text.split('-')[1]

hs_GPA = text[6].text
tuition_and_fees = text[7].text.replace("$", "").replace(",", "")
room_and_board = text[8].text.split("(")[0].replace("$", "").replace(",", "")
avg_need_based_aid_package = text[9].text.replace("$", "").replace(",", "")

bibliometric_rank = text[25].text

graduate_enrollment = text[30].text.replace(",", "")
total_enrollment = text[31].text.replace(",", "")
full_time_students = text[32].text.replace(",", "")
graduation_rate = text[33].text.replace("%", "")
rate_graduating_students_who_have_borrowed = text[34].text.replace("%", "")
avg_debt_at_graduation = text[35].text.replace("$", "").replace(",", "")

# We print out one school as data test, not important for project
print("Setting: " + setting)
print("Tuition & Fees: " + tuition_and_fees)
print("Undergraduate Enrollment: " + undergraduate_enrollment)
print("Acceptance Rate: " + acceptance_rate)
print("SAT Lower: " + sat_lower)
print("SAT Upper: " + sat_upper)
print("ACT Lower: " + act_lower)
print("ACT Upper: " + act_upper)
print("HS GPA: " + hs_GPA)
print("Tuition & Fees: " + tuition_and_fees)
print("Room & Board: " + room_and_board)
print("Average Need Based Aid Package: " + avg_need_based_aid_package)
print("Bibliometric Rank: " + bibliometric_rank)
print("Graduate Enrollment: " + graduate_enrollment)
print("Total Enrollment: " + total_enrollment)
print("Full-Time Students: " + full_time_students)
print("Graduation Rate: " + graduation_rate)
print("Percentage of Graduating Students Who've Borrowed: " + rate_graduating_students_who_have_borrowed)
print("Average Debt at Graduation: " + avg_debt_at_graduation)

University of Mary Hardin-Baylor
Ranked: 394
Setting: N/A
Tuition & Fees: 33150
Undergraduate Enrollment: 3072
Acceptance Rate: 96
SAT Lower: 970
SAT Upper: 1200
ACT Lower: 19
ACT Upper: 27
HS GPA: 3.6
Tuition & Fees: 33150
Room & Board: 10720
Average Need Based Aid Package: 19438
Bibliometric Rank: 372
Graduate Enrollment: 503
Total Enrollment: 3575
Full-Time Students: 2822
Graduation Rate: 35
Percentage of Graduating Students Who've Borrowed: 72
Average Debt at Graduation: 32840

# Scrape information from a list of colleges, temporarily saving each college's information as an .html file

In [2]:
list_test = ['https://www.usnews.com/best-colleges/princeton-university-2627',
             'https://www.usnews.com/best-colleges/university-of-california-berkeley-1312']

In [7]:
from selenium import webdriver
import requests
from bs4 import BeautifulSoup

for college in list_test:
      
    print(college)
    
    # Using Selenium we grab the html code from each university and with BeautifulSoup we use the html.parser
    driver = webdriver.Chrome()
    driver.get(college)
    with open('temporary_file.html', "w", encoding='utf-8') as f:
        f.write(driver.page_source)
    
    # We then process each class that we are looking for and set it to a variable
    college_ranking_file = open("temporary_file.html", "r", encoding="utf8")  
    contents = college_ranking_file.read() 
    soup = BeautifulSoup(contents, 'html.parser')
    
    name_full = soup.find('h1', class_='Heading-sc-1w5xk2o-0 Wakanda__Title-rzha8s-10 gTHiRT gtkLHO').text
    print(name_full)

    # We use if statements to help search for incomplete data. Many schools were missing data points
    # After a certain amount of schools, USnews simply puts a group ranking, we take the lower number and assign it to each school
    ranking_text = soup.find('span', class_='Villain__RankingSpan-sc-8s66oj-4 fDSmVR').text
    ranking = ranking_text.split(" ")[0].replace('#', "")
    if "-" in ranking:
        ranking = ranking.split("-")[0]
    print("Ranked: " + ranking)
    
    text = soup.find_all('p', class_='Paragraph-sc-1iyax29-0 kqzCwD')
    
    setting = text[0].text
    undergraduate_enrollment = text[2].text.replace(",", "")
    acceptance_rate = text[3].text.replace("%", "")
    
    if "/" in text[4].text:
            sat_lower = text[4].text.split('-')[0]
            sat_upper = sat_lower
    else:
        sat_lower = text[4].text.split('-')[0]
        sat_upper = text[4].text.split('-')[1]

    if "/" in text[5].text:
        act_lower = text[5].text.split('-')[0]
        act_upper = act_lower
    else:
        act_lower = text[5].text.split('-')[0]
        act_upper = text[5].text.split('-')[1]
    
    hs_GPA = text[6].text
    
    # Public and Private schools are not listed the same for the below variables
    if (text[1].text == text[8].text):
        school_type = 'Public'
        in_state_cost = text[1].text.replace("$", "").replace(",", "")
        out_state_cost = text[7].text.replace("$", "").replace(",", "")
        private_cost = ''
        room_and_board = text[9].text.split("(")[0].replace("$", "").replace(",", "")
        avg_need_based_aid_package = text[10].text.replace("$", "").replace(",", "")
    else:
        school_type = 'Private'
        in_state_cost = ''
        out_state_cost = ''
        private_cost = text[1].text.replace("$", "").replace(",", "")
        room_and_board = text[8].text.split("(")[0].replace("$", "").replace(",", "")
        avg_need_based_aid_package = text[9].text.replace("$", "").replace(",", "")
        
    bibliometric_rank = text[-14].text
    graduate_enrollment = text[-9].text.replace(",", "")
    total_enrollment = text[-8].text.replace(",", "")
    full_time_students = text[-7].text.replace(",", "")
    graduation_rate = text[-6].text.replace("%", "")
    rate_graduating_students_who_have_borrowed = text[-5].text.replace("%", "")
    avg_debt_at_graduation = text[-4].text.replace("$", "").replace(",", "")
    
    print("Setting: " + setting)
    print("Type: " + school_type)
    print("Private Cost: " + private_cost)
    print("In-State Cost : " + in_state_cost)
    print("Out-State Cost: " + out_state_cost)
    print("Undergraduate Enrollment: " + undergraduate_enrollment)
    print("Acceptance Rate: " + acceptance_rate)
    print("SAT Range: " + sat_range)
    print("ACT Range: " + act_range)
    print("HS GPA: " + hs_GPA)
    print("Room & Board: " + room_and_board)
    print("Average Need Based Aid Package: " + avg_need_based_aid_package)
    print("Bibliometric Rank: " + bibliometric_rank)
    print("Graduate Enrollment: " + graduate_enrollment)
    print("Total Enrollment: " + total_enrollment)
    print("Full-Time Students: " + full_time_students)
    print("Graduation Rate: " + graduation_rate)
    print("Percentage of Graduating Students Who've Borrowed: " + rate_graduating_students_who_have_borrowed)
    print("Average Debt at Graduation: " + avg_debt_at_graduation)

    print()
    print("------------------------------------------------------------------------------------")
    print()

https://www.usnews.com/best-colleges/princeton-university-2627
Princeton University
Ranked: 1
Setting: Suburban
Type: Private
Private Cost: 59710
In-State Cost : N/A
Out-State Cost: N/A
Undergraduate Enrollment: 5604
Acceptance Rate: 6
SAT Range: N/A
ACT Range: N/A
HS GPA: 3.9
Room & Board: 19380
Average Need Based Aid Package: 62844
Bibliometric Rank: 5
Graduate Enrollment: 3238
Total Enrollment: 8842
Full-Time Students: 5527
Graduation Rate: 88
Percentage of Graduating Students Who've Borrowed: 17
Average Debt at Graduation: 12500

------------------------------------------------------------------------------------

https://www.usnews.com/best-colleges/university-of-california-berkeley-1312
University of California, Berkeley
Ranked: 15
Setting: City
Type: Public
Private Cost: N/A
In-State Cost : 15891
Out-State Cost: 48465
Undergraduate Enrollment: 32831
Acceptance Rate: 11
SAT Range: N/A
ACT Range: N/A
HS GPA: 3.9
Room & Board: 22402
Average Need Based Aid Package: 31559
Bibliometric Rank: 3
Graduate Enrollment: 12914
Total Enrollment: 45745
Full-Time Students: 30568
Graduation Rate: 82
Percentage of Graduating Students Who've Borrowed: 28
Average Debt at Graduation: 16419

------------------------------------------------------------------------------------

# .csv Generating Code

In [ ]:
# Specify the .csv file you would like to save to
csv_filename = 'abc' + '.csv'

In [1]:
import pandas as pd

# Define the column names
column_names = ['School', 'School_Rank', 'School_Type','Setting', 'Address', 'City', 'State',
                'Private_Cost', 'In_State_Cost', 'Out_State_Cost', 'Average_Cost_After_Aid',
                'Undergraduate_Enrollment', 'Acceptance_Rate', 'Application_Date', 'SAT_Lower', 'SAT_Upper', 'ACT_Lower',
                'ACT_Upper', 'High_School_GPA', 'Room_and_Board', 'Average_Need_Based_Aid_Package', 'Bibliometric_rank',
                'Graduate_Enrollment', 'Total_Enrollment', 'Full_Time_Students', 'Student_Faculty_Ratio',
                'Classes_Under20_Students', 'Male_Student_Percentage', 'Female_Student_Percentage', 'Minority_Enrollment',
                'Minority_Percentage', 'Ethnic_Group_2', 'Ethnic_Percentage_2', 'Ethnic_Group_3', 'Ethnic_Percentage_3',
                'Ethnic_Group_4', 'Ethnic_Percentage_4', 'Ethnic_Group_5', 'Ethnic_Percentage_5', 'Ethnic_Group_6',
                'Ethnic_Percentage_6', 'Ethnic_Group_7', 'Ethnic_Percentage_7', 'Ethnic_Group_8', 'Ethnic_Percentage_8',
                'Graduation_Rate', 'Percentage_of_Graduating_Students_Who_Borrowed', 'Average_Debt_at_Graduation',
                'Median_Starting_Salary', 'Latitude', 'Longitude']


# Create an empty DataFrame with these columns
df = pd.DataFrame(columns=column_names)
df.to_csv(csv_filename, mode="w", header = True)

In [2]:
list_test = ['https://www.usnews.com/best-colleges/princeton-university-2627', 'https://www.usnews.com/best-colleges/massachusetts-institute-of-technology-2178', 'https://www.usnews.com/best-colleges/harvard-university-2155', 'https://www.usnews.com/best-colleges/stanford-university-1305', 'https://www.usnews.com/best-colleges/yale-university-1426', 'https://www.usnews.com/best-colleges/university-of-pennsylvania-3378', 'https://www.usnews.com/best-colleges/california-institute-of-technology-1131', 'https://www.usnews.com/best-colleges/duke-university-2920', 'https://www.usnews.com/best-colleges/brown-university-3401', 'https://www.usnews.com/best-colleges/jhu-2077', 'https://www.usnews.com/best-colleges/northwestern-university-1739', 'https://www.usnews.com/best-colleges/columbia-university-2707', 'https://www.usnews.com/best-colleges/cornell-university-2711', 'https://www.usnews.com/best-colleges/university-of-chicago-1774', 'https://www.usnews.com/best-colleges/university-of-california-berkeley-1312', 'https://www.usnews.com/best-colleges/ucla-1315', 'https://www.usnews.com/best-colleges/rice-3604', 'https://www.usnews.com/best-colleges/dartmouth-college-2573', 'https://www.usnews.com/best-colleges/vanderbilt-3535', 'https://www.usnews.com/best-colleges/university-of-notre-dame-1840', 'https://www.usnews.com/best-colleges/university-of-michigan-ann-arbor-9092', 'https://www.usnews.com/best-colleges/georgetown-university-1445', 'https://www.usnews.com/best-colleges/unc-2974', 'https://www.usnews.com/best-colleges/carnegie-mellon-university-3242', 'https://www.usnews.com/best-colleges/emory-university-1564', 'https://www.usnews.com/best-colleges/uva-6968', 'https://www.usnews.com/best-colleges/washington-university-in-st-louis-2520', 'https://www.usnews.com/best-colleges/university-of-california-davis-1313', 'https://www.usnews.com/best-colleges/university-of-california-san-diego-1317', 'https://www.usnews.com/best-colleges/university-of-florida-1535', 'https://www.usnews.com/best-colleges/university-of-southern-california-1328', 'https://www.usnews.com/best-colleges/university-of-texas-at-austin-3658', 'https://www.usnews.com/best-colleges/georgia-institute-of-technology-1569', 'https://www.usnews.com/best-colleges/university-of-california-irvine-1314', 'https://www.usnews.com/best-colleges/nyu-2785', 'https://www.usnews.com/best-colleges/university-of-california-santa-barbara-1320', 'https://www.usnews.com/best-colleges/university-of-illinois-urbanachampaign-1775', 'https://www.usnews.com/best-colleges/university-of-wisconsin-3895', 'https://www.usnews.com/best-colleges/boston-college-2128', 'https://www.usnews.com/best-colleges/rutgers-new-brunswick-6964', 'https://www.usnews.com/best-colleges/tufts-university-2219', 'https://www.usnews.com/best-colleges/university-of-washington-3798', 'https://www.usnews.com/best-colleges/boston-university-2130', 'https://www.usnews.com/best-colleges/ohio-state-6883', 'https://www.usnews.com/best-colleges/purdue-university-west-lafayette-1825', 'https://www.usnews.com/best-colleges/university-of-maryland-2103', 'https://www.usnews.com/best-colleges/lehigh-university-3289', 'https://www.usnews.com/best-colleges/texas-am-university-college-station-10366', 'https://www.usnews.com/best-colleges/university-of-georgia-1598', 'https://www.usnews.com/best-colleges/university-of-rochester-2894', 'https://www.usnews.com/best-colleges/virginia-tech-3754', 'https://www.usnews.com/best-colleges/wake-forest-2978', 'https://www.usnews.com/best-colleges/case-western-reserve-university-3024', 'https://www.usnews.com/best-colleges/florida-state-university-1489', 'https://www.usnews.com/best-colleges/northeastern-university-2199', 'https://www.usnews.com/best-colleges/university-of-minnesota-twin-cities-3969', 'https://www.usnews.com/best-colleges/william-and-mary-3705', 'https://www.usnews.com/best-colleges/stony-brook-suny-2838', 'https://www.usnews.com/best-colleges/uconn-29013', 'https://www.usnews.com/best-colleges/brandeis-university-2133', 'https://www.usnews.com/best-colleges/michigan-state-2290', 'https://www.usnews.com/best-colleges/north-carolina-state-raleigh-2972', 'https://www.usnews.com/best-colleges/penn-state-6965', 'https://www.usnews.com/best-colleges/rpi-2803', 'https://www.usnews.com/best-colleges/santa-clara-university-1326', 'https://www.usnews.com/best-colleges/university-of-california-merced-4127', 'https://www.usnews.com/best-colleges/george-washington-university-1444', 'https://www.usnews.com/best-colleges/syracuse-university-2882', 'https://www.usnews.com/best-colleges/umass-amherst-2221', 'https://www.usnews.com/best-colleges/university-of-miami-1536', 'https://www.usnews.com/best-colleges/university-of-pittsburgh-3379', 'https://www.usnews.com/best-colleges/villanova-3388', 'https://www.usnews.com/best-colleges/suny-binghamton-2836', 'https://www.usnews.com/best-colleges/indiana-university-bloomington-1809', 'https://www.usnews.com/best-colleges/tulane-university-2029', 'https://www.usnews.com/best-colleges/colorado-school-of-mines-1348', 'https://www.usnews.com/best-colleges/pepperdine-university-1264', 'https://www.usnews.com/best-colleges/stevens-institute-of-technology-2639', 'https://www.usnews.com/best-colleges/ub-9554', 'https://www.usnews.com/best-colleges/university-of-california-riverside-1316', 'https://www.usnews.com/best-colleges/university-of-delaware-1431', 'https://www.usnews.com/best-colleges/rutgers-newark-2631', 'https://www.usnews.com/best-colleges/university-of-california-santa-cruz-1321', 'https://www.usnews.com/best-colleges/university-of-illinois-chicago-1776', 'https://www.usnews.com/best-colleges/wpi-2233', 'https://www.usnews.com/best-colleges/clemson-university-3425', 'https://www.usnews.com/best-colleges/marquette-university-3863', 'https://www.usnews.com/best-colleges/njit-2621', 'https://www.usnews.com/best-colleges/fordham-university-2722', 'https://www.usnews.com/best-colleges/smu-3613', 'https://www.usnews.com/best-colleges/temple-university-3371', 'https://www.usnews.com/best-colleges/university-of-south-florida-1537', 'https://www.usnews.com/best-colleges/auburn-university-1009', 'https://www.usnews.com/best-colleges/baylor-university-6967', 'https://www.usnews.com/best-colleges/gonzaga-university-3778', 'https://www.usnews.com/best-colleges/loyola-marymount-university-11649', 'https://www.usnews.com/best-colleges/university-of-iowa-1892', 'https://www.usnews.com/best-colleges/drexel-university-3256', 'https://www.usnews.com/best-colleges/illinois-institute-of-technology-1691', 'https://www.usnews.com/best-colleges/rit-2806', 'https://www.usnews.com/best-colleges/rutgers-university-camden-4741', 'https://www.usnews.com/best-colleges/tcu-3636', 'https://www.usnews.com/best-colleges/university-of-oregon-3223', 'https://www.usnews.com/best-colleges/university-of-san-diego-10395', 'https://www.usnews.com/best-colleges/american-university-1434', 'https://www.usnews.com/best-colleges/arizona-state-university-1081', 'https://www.usnews.com/best-colleges/california-state-university-long-beach-1139', 'https://www.usnews.com/best-colleges/cuny-city-college-2688', 'https://www.usnews.com/best-colleges/gmu-3749', 'https://www.usnews.com/best-colleges/saint-louis-university-2506', 'https://www.usnews.com/best-colleges/san-diego-state-university-1151', 'https://www.usnews.com/best-colleges/university-of-colorado-boulder-1370', 'https://www.usnews.com/best-colleges/university-of-tennessee-3530', 'https://www.usnews.com/best-colleges/yeshiva-university-2903', 'https://www.usnews.com/best-colleges/byu-3670', 'https://www.usnews.com/best-colleges/howard-university-1448', 'https://www.usnews.com/best-colleges/iowa-state-university-1869', 'https://www.usnews.com/best-colleges/suny-environmental-science-and-forestry-2851', 'https://www.usnews.com/best-colleges/university-of-arizona-1083', 'https://www.usnews.com/best-colleges/university-of-new-hampshire-2589', 'https://www.usnews.com/best-colleges/university-of-san-francisco-1325', 'https://www.usnews.com/best-colleges/the-university-of-texas-at-dallas-9741', 'https://www.usnews.com/best-colleges/university-of-utah-3675', 'https://www.usnews.com/best-colleges/creighton-university-2542', 'https://www.usnews.com/best-colleges/fairfield-university-1385', 'https://www.usnews.com/best-colleges/fiu-9635', 'https://www.usnews.com/best-colleges/james-madison-university-3721', 'https://www.usnews.com/best-colleges/ucf-3954', 'https://www.usnews.com/best-colleges/university-of-denver-1371', 'https://www.usnews.com/best-colleges/university-of-missouri-2516', 'https://www.usnews.com/best-colleges/university-of-oklahoma-3184', 'https://www.usnews.com/best-colleges/university-of-south-carolina-3448', 'https://www.usnews.com/best-colleges/california-state-university-fullerton-1137', 'https://www.usnews.com/best-colleges/chapman-university-1164', 'https://www.usnews.com/best-colleges/elon-university-2927', 'https://www.usnews.com/best-colleges/miami-university-7104', 'https://www.usnews.com/best-colleges/suny-albany-2835', 'https://www.usnews.com/best-colleges/university-of-dayton-3127', 'https://www.usnews.com/best-colleges/university-of-houston-3652', 'https://www.usnews.com/best-colleges/umbc-2105', 'https://www.usnews.com/best-colleges/university-of-vermont-3696', 'https://www.usnews.com/best-colleges/clarkson-university-2699', 'https://www.usnews.com/best-colleges/clark-university-massachusetts-2139', 'https://www.usnews.com/best-colleges/loyola-university-chicago-1710', 'https://www.usnews.com/best-colleges/oregon-state-3210', 'https://www.usnews.com/best-colleges/thomas-jefferson-university-12393', 'https://www.usnews.com/best-colleges/university-of-alabama-at-birmingham-1052', 'https://www.usnews.com/best-colleges/university-of-cincinnati-3125', 'https://www.usnews.com/best-colleges/university-of-the-pacific-1329', 'https://www.usnews.com/best-colleges/vcu-3735', 'https://www.usnews.com/best-colleges/colorado-state-university-1350', 'https://www.usnews.com/best-colleges/depaul-university-1671', 'https://www.usnews.com/best-colleges/duquesne-university-3258', 'https://www.usnews.com/best-colleges/michigan-tech-2292', 'https://www.usnews.com/best-colleges/seton-hall-university-new-jersey-2632', 'https://www.usnews.com/best-colleges/simmons-university-2208', 'https://www.usnews.com/best-colleges/university-of-kansas-1948', 'https://www.usnews.com/best-colleges/university-of-rhode-island-3414', 'https://www.usnews.com/best-colleges/stockton-university-9345', 'https://www.usnews.com/best-colleges/university-of-kentucky-1989', 'https://www.usnews.com/best-colleges/umass-lowell-2161', 'https://www.usnews.com/best-colleges/university-of-nebraska-2565', 'https://www.usnews.com/best-colleges/adelphi-university-2666', 'https://www.usnews.com/best-colleges/montclair-state-university-2617', 'https://www.usnews.com/best-colleges/rowan-university-2609', 'https://www.usnews.com/best-colleges/seattle-university-3790', 'https://www.usnews.com/best-colleges/st-johns-university-new-york-2823', 'https://www.usnews.com/best-colleges/university-of-mississippi-2440', 'https://www.usnews.com/best-colleges/university-of-st-thomas-minnesota-2345', 'https://www.usnews.com/best-colleges/california-state-university-san-bernardino-1142', 'https://www.usnews.com/best-colleges/florida-am-university-1480', 'https://www.usnews.com/best-colleges/kansas-state-university-1928', 'https://www.usnews.com/best-colleges/mercer-university-1580', 'https://www.usnews.com/best-colleges/quinnipiac-university-1402', 'https://www.usnews.com/best-colleges/university-of-alabama-1051', 'https://www.usnews.com/best-colleges/university-of-hawaii-manoa-1610', 'https://www.usnews.com/best-colleges/university-of-la-verne-1216', 'https://www.usnews.com/best-colleges/the-catholic-university-of-america-1437', 'https://www.usnews.com/best-colleges/drake-university-1860', 'https://www.usnews.com/best-colleges/ohio-university-3100', 'https://www.usnews.com/best-colleges/san-francisco-state-university-1154', 'https://www.usnews.com/best-colleges/university-of-arkansas-1108', 'https://www.usnews.com/best-colleges/university-of-north-carolina-charlotte-2975', 'https://www.usnews.com/best-colleges/washington-state-3800', 'https://www.usnews.com/best-colleges/bradley-university-1641', 'https://www.usnews.com/best-colleges/california-state-university-fresno-1147', 'https://www.usnews.com/best-colleges/hofstra-university-2732', 'https://www.usnews.com/best-colleges/louisiana-state-university-baton-rouge-2010', 'https://www.usnews.com/best-colleges/missouri-university-of-science-and-technology-2517', 'https://www.usnews.com/best-colleges/oklahoma-state-3170', 'https://www.usnews.com/best-colleges/samford-university-1036', 'https://www.usnews.com/best-colleges/st-john-fisher-university-2821', 'https://www.usnews.com/best-colleges/university-of-detroit-mercy-2323', 'https://www.usnews.com/best-colleges/university-of-idaho-1626', 'https://www.usnews.com/best-colleges/east-carolina-university-2923', 'https://www.usnews.com/best-colleges/the-sage-colleges-2810', 'https://www.usnews.com/best-colleges/touro-university-10142', 'https://www.usnews.com/best-colleges/university-of-louisville-1999', 'https://www.usnews.com/best-colleges/university-of-nevada-2568', 'https://www.usnews.com/best-colleges/university-of-tulsa-3185', 'https://www.usnews.com/best-colleges/indiana-universitypurdue-university-indianapolis-1813', 'https://www.usnews.com/best-colleges/la-salle-university-3287', 'https://www.usnews.com/best-colleges/the-new-school-20662', 'https://www.usnews.com/best-colleges/robert-morris-university-pennsylvania-3359', 'https://www.usnews.com/best-colleges/university-of-north-carolina-wilmington-2984', 'https://www.usnews.com/best-colleges/valparaiso-university-1842', 'https://www.usnews.com/best-colleges/wayne-state-2329', 'https://www.usnews.com/best-colleges/xavier-university-3144', 'https://www.usnews.com/best-colleges/chatham-university-3244', 'https://www.usnews.com/best-colleges/florida-atlantic-university-1481', 'https://www.usnews.com/best-colleges/illinois-state-university-1692', 'https://www.usnews.com/best-colleges/pacific-university-3212', 'https://www.usnews.com/best-colleges/sacred-heart-university-1403', 'https://www.usnews.com/best-colleges/umass-dartmouth-2210', 'https://www.usnews.com/best-colleges/west-chester-3328', 'https://www.usnews.com/best-colleges/ball-state-university-1786', 'https://www.usnews.com/best-colleges/the-college-of-st-scholastica-2343', 'https://www.usnews.com/best-colleges/mississippi-state-2423', 'https://www.usnews.com/best-colleges/springfield-college-2211', 'https://www.usnews.com/best-colleges/st-catherine-university-2342', 'https://www.usnews.com/best-colleges/texas-tech-university-3644', 'https://www.usnews.com/best-colleges/umass-boston-2222', 'https://www.usnews.com/best-colleges/unc-greensboro-2976', 'https://www.usnews.com/best-colleges/university-of-st-thomas-texas-3654', 'https://www.usnews.com/best-colleges/university-of-wyoming-3932', 'https://www.usnews.com/best-colleges/wvu-3827', 'https://www.usnews.com/best-colleges/georgia-state-university-1574', 'https://www.usnews.com/best-colleges/kent-state-university-3051', 'https://www.usnews.com/best-colleges/misericordia-university-3247', 'https://www.usnews.com/best-colleges/nova-southeastern-university-1509', 'https://www.usnews.com/best-colleges/university-of-alabama-huntsville-1055', 'https://www.usnews.com/best-colleges/university-of-texas-rio-grande-valley-666978', 'https://www.usnews.com/best-colleges/western-carolina-university-2981', 'https://www.usnews.com/best-colleges/widener-university-3313', 'https://www.usnews.com/best-colleges/grand-valley-state-university-2268', 'https://www.usnews.com/best-colleges/azusa-pacific-university-1117', 'https://www.usnews.com/best-colleges/belmont-university-3479', 'https://www.usnews.com/best-colleges/bethel-university-minnesota-9058', 'https://www.usnews.com/best-colleges/biola-university-1122', 'https://www.usnews.com/best-colleges/gallaudet-university-1443', 'https://www.usnews.com/best-colleges/lipscomb-3486', 'https://www.usnews.com/best-colleges/university-of-colorado-denver-6740', 'https://www.usnews.com/best-colleges/university-of-new-mexico-10313', 'https://www.usnews.com/best-colleges/university-of-north-dakota-3005', 'https://www.usnews.com/best-colleges/university-of-north-florida-9841', 'https://www.usnews.com/best-colleges/the-university-of-texas-at-arlington-3656', 'https://www.usnews.com/best-colleges/western-new-england-university-2226', 'https://www.usnews.com/best-colleges/keiser-university-21519', 'https://www.usnews.com/best-colleges/maryville-saint-louis-2482', 'https://www.usnews.com/best-colleges/north-dakota-state-9265', 'https://www.usnews.com/best-colleges/northern-arizona-university-1082', 'https://www.usnews.com/best-colleges/pace-university-2791', 'https://www.usnews.com/best-colleges/sam-houston-state-3606', 'https://www.usnews.com/best-colleges/suffolk-university-2218', 'https://www.usnews.com/best-colleges/tennessee-tech-3523', 'https://www.usnews.com/best-colleges/union-university-3528', 'https://www.usnews.com/best-colleges/university-of-maine-2053', 'https://www.usnews.com/best-colleges/uw-la-crosse-3919', 'https://www.usnews.com/best-colleges/central-michigan-university-2243', 'https://www.usnews.com/best-colleges/gannon-university-3266', 'https://www.usnews.com/best-colleges/gwynedd-mercy-college-3270', 'https://www.usnews.com/best-colleges/loyola-university-new-orleans-2016', 'https://www.usnews.com/best-colleges/regis-university-1363', 'https://www.usnews.com/best-colleges/umsl-2519', 'https://www.usnews.com/best-colleges/university-of-new-england-2050', 'https://www.usnews.com/best-colleges/unt-3594', 'https://www.usnews.com/best-colleges/winstonsalem-state-2986', 'https://www.usnews.com/best-colleges/florida-institute-of-technology-1469', 'https://www.usnews.com/best-colleges/george-fox-university-3194', 'https://www.usnews.com/best-colleges/lincoln-memorial-university-3502', 'https://www.usnews.com/best-colleges/northern-illinois-university-1737', 'https://www.usnews.com/best-colleges/seattle-pacific-university-3788', 'https://www.usnews.com/best-colleges/university-of-memphis-3509', 'https://www.usnews.com/best-colleges/umkc-2518', 'https://www.usnews.com/best-colleges/unlv-2569', 'https://www.usnews.com/best-colleges/university-of-south-dakota-10300', 'https://www.usnews.com/best-colleges/utah-state-3677', 'https://www.usnews.com/best-colleges/wilkes-university-3394', 'https://www.usnews.com/best-colleges/bellarmine-university-1954', 'https://www.usnews.com/best-colleges/bowling-green-state-university-3018', 'https://www.usnews.com/best-colleges/california-state-university-east-bay-1138', 'https://www.usnews.com/best-colleges/clarke-university-1852', 'https://www.usnews.com/best-colleges/desales-university-3986', 'https://www.usnews.com/best-colleges/hampton-university-3714', 'https://www.usnews.com/best-colleges/immaculata-university-3276', 'https://www.usnews.com/best-colleges/marian-university-1821', 'https://www.usnews.com/best-colleges/north-carolina-at-2905', 'https://www.usnews.com/best-colleges/oklahoma-city-university-3166', 'https://www.usnews.com/best-colleges/old-dominion-3728', 'https://www.usnews.com/best-colleges/portland-state-3216', 'https://www.usnews.com/best-colleges/southern-illinois-university-carbondale-1758', 'https://www.usnews.com/best-colleges/texas-state-university-3615', 'https://www.usnews.com/best-colleges/university-of-st-francis-1664', 'https://www.usnews.com/best-colleges/university-of-texas-at-san-antonio-10115', 'https://www.usnews.com/best-colleges/university-of-toledo-3131', 'https://www.usnews.com/best-colleges/alvernia-university-3233', 'https://www.usnews.com/best-colleges/edgewood-college-3848', 'https://www.usnews.com/best-colleges/new-mexico-state-university-2657', 'https://www.usnews.com/best-colleges/saint-marys-university-minnesota-2380', 'https://www.usnews.com/best-colleges/south-dakota-state-3471', 'https://www.usnews.com/best-colleges/southeastern-baptist-theological-seminary-666974', 'https://www.usnews.com/best-colleges/university-of-the-incarnate-word-3578', 'https://www.usnews.com/best-colleges/aurora-university-1634', 'https://www.usnews.com/best-colleges/montana-state-2532', 'https://www.usnews.com/best-colleges/concordia-university-wisconsin-3842', 'https://www.usnews.com/best-colleges/ferris-state-university-2260', 'https://www.usnews.com/best-colleges/fgcu-32553', 'https://www.usnews.com/best-colleges/harding-university-10311', 'https://www.usnews.com/best-colleges/louisiana-tech-university-2008', 'https://www.usnews.com/best-colleges/middle-tennessee-state-university-3510', 'https://www.usnews.com/best-colleges/oakland-city-university-1824', 'https://www.usnews.com/best-colleges/radford-university-3732', 'https://www.usnews.com/best-colleges/shenandoah-university-3737', 'https://www.usnews.com/best-colleges/university-of-hartford-1422', 'https://www.usnews.com/best-colleges/university-of-houston-clear-lake-11711', 'https://www.usnews.com/best-colleges/university-of-indianapolis-1804', 'https://www.usnews.com/best-colleges/university-of-nebraska-omaha-2554', 'https://www.usnews.com/best-colleges/the-university-of-texas-at-el-paso-3661', 'https://www.usnews.com/best-colleges/western-michigan-university-2330', 'https://www.usnews.com/best-colleges/abilene-christian-3537', 'https://www.usnews.com/best-colleges/andrews-university-2238', 'https://www.usnews.com/best-colleges/campbell-university-2913', 'https://www.usnews.com/best-colleges/cleveland-state-university-3032', 'https://www.usnews.com/best-colleges/dyouville-college-2712', 'https://www.usnews.com/best-colleges/east-tennessee-state-university-3487', 'https://www.usnews.com/best-colleges/iup-3277', 'https://www.usnews.com/best-colleges/kean-university-2622', 'https://www.usnews.com/best-colleges/marymount-university-3724', 'https://www.usnews.com/best-colleges/st-ambrose-university-1889', 'https://www.usnews.com/best-colleges/university-of-puerto-rico-rio-piedras-7108', 'https://www.usnews.com/best-colleges/augusta-university-1579', 'https://www.usnews.com/best-colleges/boise-state-university-1616', 'https://www.usnews.com/best-colleges/marshall-university-3815', 'https://www.usnews.com/best-colleges/the-masters-university-and-seminary-1220', 'https://www.usnews.com/best-colleges/morgan-state-2083', 'https://www.usnews.com/best-colleges/oakland-university-2307', 'https://www.usnews.com/best-colleges/southern-illinois-university-edwardsville-1759', 'https://www.usnews.com/best-colleges/texas-womans-university-3646', 'https://www.usnews.com/best-colleges/university-of-findlay-3045', 'https://www.usnews.com/best-colleges/uw-milwaukee-3896', 'https://www.usnews.com/best-colleges/uw-oshkosh-9630', 'https://www.usnews.com/best-colleges/wichita-state-university-1950', 'https://www.usnews.com/best-colleges/lesley-university-2160', 'https://www.usnews.com/best-colleges/missouri-state-university-2503', 'https://www.usnews.com/best-colleges/baker-university-1903', 'https://www.usnews.com/best-colleges/concordia-university-irvine-29059', 'https://www.usnews.com/best-colleges/daemen-college-2808', 'https://www.usnews.com/best-colleges/university-of-louisiana-at-lafayette-2031', 'https://www.usnews.com/best-colleges/university-of-lynchburg-3720', 'https://www.usnews.com/best-colleges/university-of-tennessee-chattanooga-3529', 'https://www.usnews.com/best-colleges/eastern-kentucky-university-1963', 'https://www.usnews.com/best-colleges/georgia-southern-university-1572', 'https://www.usnews.com/best-colleges/point-park-university-3357', 'https://www.usnews.com/best-colleges/texas-am-kingsville-3639', 'https://www.usnews.com/best-colleges/university-of-hawaii-at-hilo-29020', 'https://www.usnews.com/best-colleges/university-of-northern-colorado-1349', 'https://www.usnews.com/best-colleges/university-of-southern-mississippi-2441', 'https://www.usnews.com/best-colleges/walsh-university-3135', 'https://www.usnews.com/best-colleges/gardner-webb-2929', 'https://www.usnews.com/best-colleges/william-carey-university-2447', 'https://www.usnews.com/best-colleges/arkansas-state-university-1090', 'https://www.usnews.com/best-colleges/carsonnewman-university-3481', 'https://www.usnews.com/best-colleges/clark-atlanta-university-1551', 'https://www.usnews.com/best-colleges/husson-university-2043', 'https://www.usnews.com/best-colleges/university-of-akron-3123', 'https://www.usnews.com/best-colleges/university-of-montana-2536', 'https://www.usnews.com/best-colleges/the-university-of-texas-at-tyler-11163', 'https://www.usnews.com/best-colleges/western-kentucky-university-2002', 'https://www.usnews.com/best-colleges/dominican-college-2713', 'https://www.usnews.com/best-colleges/long-island-university-667002', 'https://www.usnews.com/best-colleges/mississippi-college-2415', 'https://www.usnews.com/best-colleges/regent-university-30913', 'https://www.usnews.com/best-colleges/texas-am-commerce-3565', 'https://www.usnews.com/best-colleges/university-of-louisiana-monroe-2020', 'https://www.usnews.com/best-colleges/umes-2106', 'https://www.usnews.com/best-colleges/dallas-baptist-university-3560', 'https://www.usnews.com/best-colleges/eastern-michigan-university-2259', 'https://www.usnews.com/best-colleges/college-of-mount-st-joseph-3033', 'https://www.usnews.com/best-colleges/tarleton-3631', 'https://www.usnews.com/best-colleges/university-of-mary-2992', 'https://www.usnews.com/best-colleges/wingate-university-2985', 'https://www.usnews.com/best-colleges/pontifical-catholic-university-of-puerto-rico-ponce-3936', 'https://www.usnews.com/best-colleges/indiana-state-9563', 'https://www.usnews.com/best-colleges/northern-kentucky-university-9275', 'https://www.usnews.com/best-colleges/palm-beach-atlantic-university-8849', 'https://www.usnews.com/best-colleges/trevecca-nazarene-university-3526', 'https://www.usnews.com/best-colleges/university-of-south-alabama-1057', 'https://www.usnews.com/best-colleges/university-of-west-georgia-1601', 'https://www.usnews.com/best-colleges/university-of-alaska-fairbanks-1063', 'https://www.usnews.com/best-colleges/university-of-bridgeport-1416', 'https://www.usnews.com/best-colleges/roosevelt-university-1749', 'https://www.usnews.com/best-colleges/saint-leo-university-1526', 'https://www.usnews.com/best-colleges/university-of-arkansas-at-little-rock-1101', 'https://www.usnews.com/best-colleges/university-of-michigan-flint-2327', 'https://www.usnews.com/best-colleges/alabama-state-university-1005', 'https://www.usnews.com/best-colleges/american-international-college-2114', 'https://www.usnews.com/best-colleges/barry-university-1466', 'https://www.usnews.com/best-colleges/belhaven-2397', 'https://www.usnews.com/best-colleges/brenau-university-1556', 'https://www.usnews.com/best-colleges/briar-cliff-university-1846', 'https://www.usnews.com/best-colleges/capitol-technology-university-1436', 'https://www.usnews.com/best-colleges/colorado-technical-university-10148', 'https://www.usnews.com/best-colleges/grand-canyon-university-1074', 'https://www.usnews.com/best-colleges/hardin-simmons-university-3571', 'https://www.usnews.com/best-colleges/idaho-state-university-1620', 'https://www.usnews.com/best-colleges/jackson-state-2410', 'https://www.usnews.com/best-colleges/kennesaw-state-university-1577', 'https://www.usnews.com/best-colleges/lamar-university-3581', 'https://www.usnews.com/best-colleges/liberty-university-10392', 'https://www.usnews.com/best-colleges/mary-baldwin-university-3723', 'https://www.usnews.com/best-colleges/national-louis-university-1733', 'https://www.usnews.com/best-colleges/our-lady-of-the-lake-university-3598', 'https://www.usnews.com/best-colleges/prairie-view-am-university-3630', 'https://www.usnews.com/best-colleges/purdue-university-global-957121', 'https://www.usnews.com/best-colleges/south-college-4938', 'https://www.usnews.com/best-colleges/southeastern-university-1521', 'https://www.usnews.com/best-colleges/southern-university-9636', 'https://www.usnews.com/best-colleges/st-thomas-university-1468', 'https://www.usnews.com/best-colleges/tennessee-state-3522', 'https://www.usnews.com/best-colleges/texas-am-university-corpus-christi-11161', 'https://www.usnews.com/best-colleges/texas-southern-university-3642', 'https://www.usnews.com/best-colleges/texas-wesleyan-university-3645', 'https://www.usnews.com/best-colleges/trinity-international-university-1772', 'https://www.usnews.com/best-colleges/universidad-ana-g-mendez-gurabo-campus-11719', 'https://www.usnews.com/best-colleges/university-of-central-arkansas-1092', 'https://www.usnews.com/best-colleges/university-of-charleston-3818', 'https://www.usnews.com/best-colleges/university-of-colorado-colorado-springs-4509', 'https://www.usnews.com/best-colleges/mary-hardin-baylor-3588', 'https://www.usnews.com/best-colleges/university-of-new-orleans-2015', 'https://www.usnews.com/best-colleges/university-of-pikeville-1980', 'https://www.usnews.com/best-colleges/university-of-the-cumberlands-1962', 'https://www.usnews.com/best-colleges/valdosta-state-university-1599', 'https://www.usnews.com/best-colleges/william-woods-university-2525', 'https://www.usnews.com/best-colleges/wilmington-university-7948', 'https://www.usnews.com/best-colleges/wright-state-9168', 'https://www.usnews.com/best-colleges/albizu-university-miami-667083', 'https://www.usnews.com/best-colleges/alliant-international-university-1158', 'https://www.usnews.com/best-colleges/loma-linda-university-1218', 'https://www.usnews.com/best-colleges/pontifical-catholic-university-of-puerto-rico-arecibo-667004']

In [9]:
list_completed = ['https://www.usnews.com/best-colleges/princeton-university-2627', 'https://www.usnews.com/best-colleges/massachusetts-institute-of-technology-2178', 'https://www.usnews.com/best-colleges/harvard-university-2155', 'https://www.usnews.com/best-colleges/stanford-university-1305', 'https://www.usnews.com/best-colleges/yale-university-1426', 'https://www.usnews.com/best-colleges/university-of-pennsylvania-3378', 'https://www.usnews.com/best-colleges/california-institute-of-technology-1131', 'https://www.usnews.com/best-colleges/duke-university-2920', 'https://www.usnews.com/best-colleges/brown-university-3401', 'https://www.usnews.com/best-colleges/jhu-2077', 'https://www.usnews.com/best-colleges/northwestern-university-1739', 'https://www.usnews.com/best-colleges/columbia-university-2707', 'https://www.usnews.com/best-colleges/cornell-university-2711', 'https://www.usnews.com/best-colleges/university-of-chicago-1774', 'https://www.usnews.com/best-colleges/university-of-california-berkeley-1312', 'https://www.usnews.com/best-colleges/ucla-1315', 'https://www.usnews.com/best-colleges/rice-3604', 'https://www.usnews.com/best-colleges/dartmouth-college-2573', 'https://www.usnews.com/best-colleges/vanderbilt-3535', 'https://www.usnews.com/best-colleges/university-of-notre-dame-1840', 'https://www.usnews.com/best-colleges/university-of-michigan-ann-arbor-9092', 'https://www.usnews.com/best-colleges/georgetown-university-1445', 'https://www.usnews.com/best-colleges/unc-2974', 'https://www.usnews.com/best-colleges/carnegie-mellon-university-3242', 'https://www.usnews.com/best-colleges/emory-university-1564', 'https://www.usnews.com/best-colleges/uva-6968', 'https://www.usnews.com/best-colleges/washington-university-in-st-louis-2520', 'https://www.usnews.com/best-colleges/university-of-california-davis-1313', 'https://www.usnews.com/best-colleges/university-of-california-san-diego-1317', 'https://www.usnews.com/best-colleges/university-of-florida-1535', 'https://www.usnews.com/best-colleges/university-of-southern-california-1328', 'https://www.usnews.com/best-colleges/university-of-texas-at-austin-3658', 'https://www.usnews.com/best-colleges/georgia-institute-of-technology-1569', 'https://www.usnews.com/best-colleges/university-of-california-irvine-1314', 'https://www.usnews.com/best-colleges/nyu-2785', 'https://www.usnews.com/best-colleges/university-of-california-santa-barbara-1320', 'https://www.usnews.com/best-colleges/university-of-illinois-urbanachampaign-1775', 'https://www.usnews.com/best-colleges/university-of-wisconsin-3895', 'https://www.usnews.com/best-colleges/boston-college-2128', 'https://www.usnews.com/best-colleges/rutgers-new-brunswick-6964', 'https://www.usnews.com/best-colleges/tufts-university-2219', 'https://www.usnews.com/best-colleges/university-of-washington-3798', 'https://www.usnews.com/best-colleges/boston-university-2130', 'https://www.usnews.com/best-colleges/ohio-state-6883', 'https://www.usnews.com/best-colleges/purdue-university-west-lafayette-1825', 'https://www.usnews.com/best-colleges/university-of-maryland-2103', 'https://www.usnews.com/best-colleges/lehigh-university-3289', 'https://www.usnews.com/best-colleges/texas-am-university-college-station-10366', 'https://www.usnews.com/best-colleges/university-of-georgia-1598', 'https://www.usnews.com/best-colleges/university-of-rochester-2894', 'https://www.usnews.com/best-colleges/virginia-tech-3754', 'https://www.usnews.com/best-colleges/wake-forest-2978', 'https://www.usnews.com/best-colleges/case-western-reserve-university-3024', 'https://www.usnews.com/best-colleges/florida-state-university-1489', 'https://www.usnews.com/best-colleges/northeastern-university-2199', 'https://www.usnews.com/best-colleges/university-of-minnesota-twin-cities-3969', 'https://www.usnews.com/best-colleges/william-and-mary-3705', 'https://www.usnews.com/best-colleges/stony-brook-suny-2838', 'https://www.usnews.com/best-colleges/uconn-29013', 'https://www.usnews.com/best-colleges/brandeis-university-2133', 'https://www.usnews.com/best-colleges/michigan-state-2290', 'https://www.usnews.com/best-colleges/north-carolina-state-raleigh-2972', 'https://www.usnews.com/best-colleges/penn-state-6965', 'https://www.usnews.com/best-colleges/rpi-2803', 'https://www.usnews.com/best-colleges/santa-clara-university-1326', 'https://www.usnews.com/best-colleges/university-of-california-merced-4127', 'https://www.usnews.com/best-colleges/george-washington-university-1444', 'https://www.usnews.com/best-colleges/syracuse-university-2882', 'https://www.usnews.com/best-colleges/umass-amherst-2221', 'https://www.usnews.com/best-colleges/university-of-miami-1536', 'https://www.usnews.com/best-colleges/university-of-pittsburgh-3379', 'https://www.usnews.com/best-colleges/villanova-3388', 'https://www.usnews.com/best-colleges/suny-binghamton-2836', 'https://www.usnews.com/best-colleges/indiana-university-bloomington-1809', 'https://www.usnews.com/best-colleges/tulane-university-2029', 'https://www.usnews.com/best-colleges/colorado-school-of-mines-1348', 'https://www.usnews.com/best-colleges/pepperdine-university-1264', 'https://www.usnews.com/best-colleges/stevens-institute-of-technology-2639', 'https://www.usnews.com/best-colleges/ub-9554', 'https://www.usnews.com/best-colleges/university-of-california-riverside-1316', 'https://www.usnews.com/best-colleges/university-of-delaware-1431', 'https://www.usnews.com/best-colleges/rutgers-newark-2631', 'https://www.usnews.com/best-colleges/university-of-california-santa-cruz-1321', 'https://www.usnews.com/best-colleges/university-of-illinois-chicago-1776', 'https://www.usnews.com/best-colleges/wpi-2233', 'https://www.usnews.com/best-colleges/clemson-university-3425', 'https://www.usnews.com/best-colleges/marquette-university-3863', 'https://www.usnews.com/best-colleges/njit-2621', 'https://www.usnews.com/best-colleges/fordham-university-2722', 'https://www.usnews.com/best-colleges/smu-3613', 'https://www.usnews.com/best-colleges/temple-university-3371', 'https://www.usnews.com/best-colleges/university-of-south-florida-1537', 'https://www.usnews.com/best-colleges/auburn-university-1009', 'https://www.usnews.com/best-colleges/baylor-university-6967', 'https://www.usnews.com/best-colleges/gonzaga-university-3778', 'https://www.usnews.com/best-colleges/loyola-marymount-university-11649', 'https://www.usnews.com/best-colleges/university-of-iowa-1892', 'https://www.usnews.com/best-colleges/drexel-university-3256', 'https://www.usnews.com/best-colleges/illinois-institute-of-technology-1691', 'https://www.usnews.com/best-colleges/rit-2806', 'https://www.usnews.com/best-colleges/rutgers-university-camden-4741', 'https://www.usnews.com/best-colleges/tcu-3636', 'https://www.usnews.com/best-colleges/university-of-oregon-3223', 'https://www.usnews.com/best-colleges/university-of-san-diego-10395', 'https://www.usnews.com/best-colleges/american-university-1434', 'https://www.usnews.com/best-colleges/arizona-state-university-1081', 'https://www.usnews.com/best-colleges/california-state-university-long-beach-1139', 'https://www.usnews.com/best-colleges/cuny-city-college-2688', 'https://www.usnews.com/best-colleges/gmu-3749', 'https://www.usnews.com/best-colleges/saint-louis-university-2506', 'https://www.usnews.com/best-colleges/san-diego-state-university-1151', 'https://www.usnews.com/best-colleges/university-of-colorado-boulder-1370', 'https://www.usnews.com/best-colleges/university-of-tennessee-3530', 'https://www.usnews.com/best-colleges/yeshiva-university-2903', 'https://www.usnews.com/best-colleges/byu-3670', 'https://www.usnews.com/best-colleges/howard-university-1448', 'https://www.usnews.com/best-colleges/iowa-state-university-1869', 'https://www.usnews.com/best-colleges/suny-environmental-science-and-forestry-2851', 'https://www.usnews.com/best-colleges/university-of-arizona-1083', 'https://www.usnews.com/best-colleges/university-of-new-hampshire-2589', 'https://www.usnews.com/best-colleges/university-of-san-francisco-1325', 'https://www.usnews.com/best-colleges/the-university-of-texas-at-dallas-9741', 'https://www.usnews.com/best-colleges/university-of-utah-3675', 'https://www.usnews.com/best-colleges/creighton-university-2542', 'https://www.usnews.com/best-colleges/fairfield-university-1385', 'https://www.usnews.com/best-colleges/fiu-9635', 'https://www.usnews.com/best-colleges/james-madison-university-3721', 'https://www.usnews.com/best-colleges/ucf-3954', 'https://www.usnews.com/best-colleges/university-of-denver-1371', 'https://www.usnews.com/best-colleges/university-of-missouri-2516', 'https://www.usnews.com/best-colleges/university-of-oklahoma-3184', 'https://www.usnews.com/best-colleges/university-of-south-carolina-3448', 'https://www.usnews.com/best-colleges/california-state-university-fullerton-1137', 'https://www.usnews.com/best-colleges/chapman-university-1164', 'https://www.usnews.com/best-colleges/elon-university-2927', 'https://www.usnews.com/best-colleges/miami-university-7104', 'https://www.usnews.com/best-colleges/suny-albany-2835', 'https://www.usnews.com/best-colleges/university-of-dayton-3127', 'https://www.usnews.com/best-colleges/university-of-houston-3652', 'https://www.usnews.com/best-colleges/umbc-2105', 'https://www.usnews.com/best-colleges/university-of-vermont-3696', 'https://www.usnews.com/best-colleges/clarkson-university-2699', 'https://www.usnews.com/best-colleges/clark-university-massachusetts-2139', 'https://www.usnews.com/best-colleges/loyola-university-chicago-1710', 'https://www.usnews.com/best-colleges/oregon-state-3210', 'https://www.usnews.com/best-colleges/thomas-jefferson-university-12393', 'https://www.usnews.com/best-colleges/university-of-alabama-at-birmingham-1052', 'https://www.usnews.com/best-colleges/university-of-cincinnati-3125', 'https://www.usnews.com/best-colleges/university-of-the-pacific-1329', 'https://www.usnews.com/best-colleges/vcu-3735', 'https://www.usnews.com/best-colleges/colorado-state-university-1350', 'https://www.usnews.com/best-colleges/depaul-university-1671', 'https://www.usnews.com/best-colleges/duquesne-university-3258', 'https://www.usnews.com/best-colleges/michigan-tech-2292', 'https://www.usnews.com/best-colleges/seton-hall-university-new-jersey-2632', 'https://www.usnews.com/best-colleges/simmons-university-2208', 'https://www.usnews.com/best-colleges/university-of-kansas-1948', 'https://www.usnews.com/best-colleges/university-of-rhode-island-3414', 'https://www.usnews.com/best-colleges/stockton-university-9345', 'https://www.usnews.com/best-colleges/university-of-kentucky-1989', 'https://www.usnews.com/best-colleges/umass-lowell-2161', 'https://www.usnews.com/best-colleges/university-of-nebraska-2565', 'https://www.usnews.com/best-colleges/adelphi-university-2666', 'https://www.usnews.com/best-colleges/montclair-state-university-2617', 'https://www.usnews.com/best-colleges/rowan-university-2609', 'https://www.usnews.com/best-colleges/seattle-university-3790', 'https://www.usnews.com/best-colleges/st-johns-university-new-york-2823', 'https://www.usnews.com/best-colleges/university-of-mississippi-2440', 'https://www.usnews.com/best-colleges/university-of-st-thomas-minnesota-2345', 'https://www.usnews.com/best-colleges/california-state-university-san-bernardino-1142', 'https://www.usnews.com/best-colleges/florida-am-university-1480', 'https://www.usnews.com/best-colleges/kansas-state-university-1928', 'https://www.usnews.com/best-colleges/mercer-university-1580', 'https://www.usnews.com/best-colleges/quinnipiac-university-1402', 'https://www.usnews.com/best-colleges/university-of-alabama-1051', 'https://www.usnews.com/best-colleges/university-of-hawaii-manoa-1610', 'https://www.usnews.com/best-colleges/university-of-la-verne-1216', 'https://www.usnews.com/best-colleges/the-catholic-university-of-america-1437', 'https://www.usnews.com/best-colleges/drake-university-1860', 'https://www.usnews.com/best-colleges/ohio-university-3100', 'https://www.usnews.com/best-colleges/san-francisco-state-university-1154', 'https://www.usnews.com/best-colleges/university-of-arkansas-1108', 'https://www.usnews.com/best-colleges/university-of-north-carolina-charlotte-2975', 'https://www.usnews.com/best-colleges/washington-state-3800', 'https://www.usnews.com/best-colleges/bradley-university-1641', 'https://www.usnews.com/best-colleges/california-state-university-fresno-1147', 'https://www.usnews.com/best-colleges/hofstra-university-2732', 'https://www.usnews.com/best-colleges/louisiana-state-university-baton-rouge-2010', 'https://www.usnews.com/best-colleges/missouri-university-of-science-and-technology-2517', 'https://www.usnews.com/best-colleges/oklahoma-state-3170', 'https://www.usnews.com/best-colleges/samford-university-1036', 'https://www.usnews.com/best-colleges/st-john-fisher-university-2821', 'https://www.usnews.com/best-colleges/university-of-detroit-mercy-2323', 'https://www.usnews.com/best-colleges/university-of-idaho-1626', 'https://www.usnews.com/best-colleges/east-carolina-university-2923', 'https://www.usnews.com/best-colleges/the-sage-colleges-2810', 'https://www.usnews.com/best-colleges/touro-university-10142', 'https://www.usnews.com/best-colleges/university-of-louisville-1999', 'https://www.usnews.com/best-colleges/university-of-nevada-2568', 'https://www.usnews.com/best-colleges/university-of-tulsa-3185', 'https://www.usnews.com/best-colleges/indiana-universitypurdue-university-indianapolis-1813', 'https://www.usnews.com/best-colleges/la-salle-university-3287', 'https://www.usnews.com/best-colleges/the-new-school-20662', 'https://www.usnews.com/best-colleges/robert-morris-university-pennsylvania-3359', 'https://www.usnews.com/best-colleges/university-of-north-carolina-wilmington-2984', 'https://www.usnews.com/best-colleges/valparaiso-university-1842', 'https://www.usnews.com/best-colleges/wayne-state-2329', 'https://www.usnews.com/best-colleges/xavier-university-3144', 'https://www.usnews.com/best-colleges/chatham-university-3244', 'https://www.usnews.com/best-colleges/florida-atlantic-university-1481', 'https://www.usnews.com/best-colleges/illinois-state-university-1692', 'https://www.usnews.com/best-colleges/pacific-university-3212', 'https://www.usnews.com/best-colleges/sacred-heart-university-1403', 'https://www.usnews.com/best-colleges/umass-dartmouth-2210', 'https://www.usnews.com/best-colleges/west-chester-3328', 'https://www.usnews.com/best-colleges/ball-state-university-1786', 'https://www.usnews.com/best-colleges/the-college-of-st-scholastica-2343', 'https://www.usnews.com/best-colleges/mississippi-state-2423', 'https://www.usnews.com/best-colleges/springfield-college-2211', 'https://www.usnews.com/best-colleges/st-catherine-university-2342', 'https://www.usnews.com/best-colleges/texas-tech-university-3644', 'https://www.usnews.com/best-colleges/umass-boston-2222', 'https://www.usnews.com/best-colleges/unc-greensboro-2976', 'https://www.usnews.com/best-colleges/university-of-st-thomas-texas-3654', 'https://www.usnews.com/best-colleges/university-of-wyoming-3932', 'https://www.usnews.com/best-colleges/wvu-3827', 'https://www.usnews.com/best-colleges/georgia-state-university-1574', 'https://www.usnews.com/best-colleges/kent-state-university-3051', 'https://www.usnews.com/best-colleges/misericordia-university-3247', 'https://www.usnews.com/best-colleges/nova-southeastern-university-1509', 'https://www.usnews.com/best-colleges/university-of-alabama-huntsville-1055', 'https://www.usnews.com/best-colleges/university-of-texas-rio-grande-valley-666978', 'https://www.usnews.com/best-colleges/western-carolina-university-2981', 'https://www.usnews.com/best-colleges/widener-university-3313', 'https://www.usnews.com/best-colleges/grand-valley-state-university-2268', 'https://www.usnews.com/best-colleges/azusa-pacific-university-1117', 'https://www.usnews.com/best-colleges/belmont-university-3479', 'https://www.usnews.com/best-colleges/bethel-university-minnesota-9058', 'https://www.usnews.com/best-colleges/biola-university-1122', 'https://www.usnews.com/best-colleges/gallaudet-university-1443', 'https://www.usnews.com/best-colleges/lipscomb-3486', 'https://www.usnews.com/best-colleges/university-of-colorado-denver-6740', 'https://www.usnews.com/best-colleges/university-of-new-mexico-10313', 'https://www.usnews.com/best-colleges/university-of-north-dakota-3005', 'https://www.usnews.com/best-colleges/university-of-north-florida-9841', 'https://www.usnews.com/best-colleges/the-university-of-texas-at-arlington-3656', 'https://www.usnews.com/best-colleges/western-new-england-university-2226', 'https://www.usnews.com/best-colleges/keiser-university-21519', 'https://www.usnews.com/best-colleges/maryville-saint-louis-2482', 'https://www.usnews.com/best-colleges/north-dakota-state-9265', 'https://www.usnews.com/best-colleges/northern-arizona-university-1082', 'https://www.usnews.com/best-colleges/pace-university-2791', 'https://www.usnews.com/best-colleges/sam-houston-state-3606', 'https://www.usnews.com/best-colleges/suffolk-university-2218', 'https://www.usnews.com/best-colleges/tennessee-tech-3523', 'https://www.usnews.com/best-colleges/union-university-3528', 'https://www.usnews.com/best-colleges/university-of-maine-2053', 'https://www.usnews.com/best-colleges/uw-la-crosse-3919', 'https://www.usnews.com/best-colleges/central-michigan-university-2243', 'https://www.usnews.com/best-colleges/gannon-university-3266', 'https://www.usnews.com/best-colleges/gwynedd-mercy-college-3270', 'https://www.usnews.com/best-colleges/loyola-university-new-orleans-2016', 'https://www.usnews.com/best-colleges/regis-university-1363', 'https://www.usnews.com/best-colleges/umsl-2519', 'https://www.usnews.com/best-colleges/university-of-new-england-2050', 'https://www.usnews.com/best-colleges/unt-3594', 'https://www.usnews.com/best-colleges/winstonsalem-state-2986', 'https://www.usnews.com/best-colleges/florida-institute-of-technology-1469', 'https://www.usnews.com/best-colleges/george-fox-university-3194', 'https://www.usnews.com/best-colleges/lincoln-memorial-university-3502', 'https://www.usnews.com/best-colleges/northern-illinois-university-1737', 'https://www.usnews.com/best-colleges/seattle-pacific-university-3788', 'https://www.usnews.com/best-colleges/university-of-memphis-3509', 'https://www.usnews.com/best-colleges/umkc-2518', 'https://www.usnews.com/best-colleges/unlv-2569', 'https://www.usnews.com/best-colleges/university-of-south-dakota-10300', 'https://www.usnews.com/best-colleges/utah-state-3677', 'https://www.usnews.com/best-colleges/wilkes-university-3394', 'https://www.usnews.com/best-colleges/bellarmine-university-1954', 'https://www.usnews.com/best-colleges/bowling-green-state-university-3018', 'https://www.usnews.com/best-colleges/california-state-university-east-bay-1138', 'https://www.usnews.com/best-colleges/clarke-university-1852', 'https://www.usnews.com/best-colleges/desales-university-3986', 'https://www.usnews.com/best-colleges/hampton-university-3714', 'https://www.usnews.com/best-colleges/immaculata-university-3276', 'https://www.usnews.com/best-colleges/marian-university-1821', 'https://www.usnews.com/best-colleges/north-carolina-at-2905', 'https://www.usnews.com/best-colleges/oklahoma-city-university-3166', 'https://www.usnews.com/best-colleges/old-dominion-3728', 'https://www.usnews.com/best-colleges/portland-state-3216', 'https://www.usnews.com/best-colleges/southern-illinois-university-carbondale-1758', 'https://www.usnews.com/best-colleges/texas-state-university-3615', 'https://www.usnews.com/best-colleges/university-of-st-francis-1664', 'https://www.usnews.com/best-colleges/university-of-texas-at-san-antonio-10115', 'https://www.usnews.com/best-colleges/university-of-toledo-3131', 'https://www.usnews.com/best-colleges/alvernia-university-3233', 'https://www.usnews.com/best-colleges/edgewood-college-3848']

In [4]:
list_skipped = []

In [8]:
import mysql.connector
from mysql.connector import Error
import pgeocode
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import pandas as pd

# Iterate through each college url in list_test
for college in list_test:
    
    # Determine if college should be processed
    if college in list_completed:
        print(college + " has already been processed")
    elif college in list_skipped:
        print(college + " has been skipped")
    else:
        # Open the college url
        driver = webdriver.Chrome()
        driver.get(college)
        html_source = driver.page_source
        
        # Create soup variable
        soup = BeautifulSoup(html_source, 'html.parser')
    
        # Scrape name of college
        name_full = soup.find('h1', class_='Heading-sc-1w5xk2o-0 Wakanda__Title-rzha8s-10 gTHiRT gtkLHO').text

        # Scrape ranking of college
        ranking_text = soup.find('span', class_='Villain__RankingSpan-sc-8s66oj-4 fDSmVR').text
        ranking = ranking_text.split(" ")[0].replace('#', "")
        if "-" in ranking:
            ranking = ranking.split("-")[0]

        # Begin scraping college data, the majority of which is within class_='Paragraph-sc-1iyax29-0 kqzCwD'
        text = soup.find_all('p', class_='Paragraph-sc-1iyax29-0 kqzCwD')

        setting = text[0].text
        undergraduate_enrollment = text[2].text.replace(",", "")
        acceptance_rate = text[3].text.replace("%", "")

        if "/" in text[4].text:
                sat_lower = ''
                sat_upper = ''
        else:
            sat_lower = text[4].text.split('-')[0]
            sat_upper = text[4].text.split('-')[1]

        if "/" in text[5].text:
            act_lower = ''
            act_upper = ''
        else:
            act_lower = text[5].text.split('-')[0]
            act_upper = text[5].text.split('-')[1]

        
        if '.' in text[6].text:
            hs_GPA = text[6].text
        else:
            hs_GPA = ''
    
        # Determine if School is Public or Private
        if (text[1].text == text[8].text):
            school_type = 'Public'
            in_state_cost = text[1].text.replace("$", "").replace(",", "")
            out_state_cost = text[7].text.replace("$", "").replace(",", "")
            private_cost = ''
            room_and_board = text[9].text.split("(")[0].replace("$", "").replace(",", "")
            avg_need_based_aid_package = text[10].text.replace("$", "").replace(",", "")
        else:
            school_type = 'Private'
            in_state_cost = ''
            out_state_cost = ''
            private_cost = text[1].text.replace("$", "").replace(",", "")
            room_and_board = text[8].text.split("(")[0].replace("$", "").replace(",", "")
            avg_need_based_aid_package = text[9].text.replace("$", "").replace(",", "")
        
        # Handle null values for room_and_board and avg_need_based_aid_package
        if (room_and_board == 'N/A'):
            room_and_board = ''
        if (avg_need_based_aid_package == 'N/A'):
            avg_need_based_aid_package = ''

        # Additional School Data
        bibliometric_rank = text[-14].text
        graduate_enrollment = text[-9].text.replace(",", "")
        total_enrollment = text[-8].text.replace(",", "")
        full_time_students = text[-7].text.replace(",", "")
        graduation_rate = text[-6].text.replace("%", "")
        rate_graduating_students_who_have_borrowed = text[-5].text.replace("%", "")
        avg_debt_at_graduation = text[-4].text.replace("$", "").replace(",", "")

        
        # Print statements used to debug
        print(name_full)
        print("Ranked: " + ranking)
#         print("Setting: " + setting)
        print("Type: " + school_type)
#         print("Private Cost: " + private_cost)
#         print("In-State Cost : " + in_state_cost)
#         print("Out-State Cost: " + out_state_cost)
#         print("Undergraduate Enrollment: " + undergraduate_enrollment)
#         print("Acceptance Rate: " + acceptance_rate)
#         print("SAT Range: " + sat_range)
#         print("ACT Range: " + act_range)
#         print("HS GPA: " + hs_GPA)
#         print("Room & Board: " + room_and_board)
#         print("Average Need Based Aid Package: " + avg_need_based_aid_package)
#         print("Bibliometric Rank: " + bibliometric_rank)
#         print("Graduate Enrollment: " + graduate_enrollment)
#         print("Total Enrollment: " + total_enrollment)
#         print("Full-Time Students: " + full_time_students)
#         print("Graduation Rate: " + graduation_rate)
#         print("Percentage of Graduating Students Who've Borrowed: " + rate_graduating_students_who_have_borrowed)
#         print("Average Debt at Graduation: " + avg_debt_at_graduation)
        print("")
        print("------------------------------------------------------------------------------------------------")
        print("")
        
        # Scrape location information
        address = soup.find('div', class_='OverviewContent__AddressDiv-sc-1yondsr-5 kiOfwR').text
        z = address.split(', ')
        city = z[-3]
        state = z[-2]
        zipcode = z[-1]
        
        # Scrape additional college data
        app_date = soup.find('p', class_='ApplyingSection__DataHeader-sc-2strss-7 hRHtQv').text.replace('.','')
        avg_cost_after_aid = float(soup.find('p', class_="CostSection__DataHeader-coeai5-0 fGJUFn").text.replace('$','').replace(',',''))
        student_faculty_ratio = (soup.find_all('p', class_= "AcademicSection__DataHeader-sc-1g5x16k-5 cKgZfy")[1].text.split(':')[0])
        class_under20 = (soup.find_all('p', class_= "AcademicSection__DataHeader-sc-1g5x16k-5 cKgZfy")[2].text.replace('%',''))
        
        # Scrape Male/Female Ratios
            ## Male:Female Ratio Section uses 'dee_' and 'tag_' variables
        dee1 = soup.find('div', class_= "BarChartStacked__Legend-wgxhoq-4 iLdLaQ")
        tag1 = dee1.find_all('b')
        male_percent = float(tag1[0].text.replace('%',''))
        dee2 = soup.find('div', class_= "BarChartStacked__Legend-wgxhoq-4 iLdLaQ")
        tag2 = dee2.find_all('b')
        female_percent = float(tag2[1].text.replace('%',''))
        
        # Scrape Ethnicity Data
            ## Ethnicity Section uses 't_', 'group_', and 'rank_' variables
        t=soup.find('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fQzOWy fsMCCD")
        group = t.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
        rank_1 = int(t.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        
        
        # Scrape ethnicity data that is under the class 'Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI'
        # If data not available, assign empty string to the variables
        t2_and_greater = soup.find_all('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI")
        
        t2 = t2_and_greater[0]
        group2 = t2.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
        rank_2 = int(t2.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        
        if (len(t2_and_greater) > 1):
            t3=soup.find_all('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI")[1]
            group3 = t3.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
            rank_3 = int(t3.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        else:
            t3 = ''
            group3 = ''
            rank_3 = ''
        
        if (len(t2_and_greater) > 2):
            t4=soup.find_all('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI")[2]
            group4 = t4.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
            rank_4 = int(t4.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        else:
            t4 = ''
            group4 = ''
            rank_4 = ''
        
        if (len(t2_and_greater) > 3):
            t5=soup.find_all('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI")[3]
            group5 = t5.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
            rank_5 = int(t5.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        else:
            t5 = ''
            group5 = ''
            rank_5 = ''
        
        if (len(t2_and_greater) > 4):
            t6=soup.find_all('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI")[4]
            group6 = t6.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
            rank_6 = int(t6.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        else:
            t6 = ''
            group6 = ''
            rank_6 = ''
        
        if (len(t2_and_greater) > 5):
            t7=soup.find_all('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 fwvgzM cuHcPI")[5]
            group7 = t7.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
            rank_7 = int(t7.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        else:
            t7 = ''
            group7 = ''
            rank_7 = ''
        
        t8=soup.find('div', class_="Box-w0dun1-0 Key__ItemBox-sc-12afmmk-0 gCRfsj cuHcPI")
        group8 = t8.find('p', class_="Paragraph-sc-1iyax29-0 Key__Title-sc-12afmmk-1 dDlIGP hWVZdP").text
        rank_8 = int(t8.find('p', class_="Paragraph-sc-1iyax29-0 Key__Data-sc-12afmmk-3 dDlIGP eoKXJn").text.replace('%',''))
        
        # Scrape median starting salary
        median_starting = (soup.find('p', class_='AfterCollegeSection__DataHeader-czoza-1 iYbKOL').text.strip('.').replace('$','').replace(',',''))
        
        # Latitude and longitude data
            ## Geocode section uses 'nomi' and 'geo' variables
        nomi = pgeocode.Nominatim('us')
        geo = nomi.query_postal_code(zipcode)
        latitude = float(geo['latitude'])
        longitude = float(geo['longitude'])
        
        # Prepare data for appending to dataframe
        school_data = [[name_full, ranking, school_type, setting, address, city, state,
                        private_cost, in_state_cost, out_state_cost, avg_cost_after_aid, 
                        undergraduate_enrollment, acceptance_rate, app_date, sat_lower, sat_upper, act_lower, act_upper,
                        hs_GPA, room_and_board, avg_need_based_aid_package, bibliometric_rank, graduate_enrollment,
                        total_enrollment, full_time_students, student_faculty_ratio, class_under20, male_percent,
                        female_percent, group, rank_1, group2, rank_2, group3, rank_3, group4, rank_4, group5, rank_5,
                        group6, rank_6, group7, rank_7, group8, rank_8, graduation_rate,
                        rate_graduating_students_who_have_borrowed, avg_debt_at_graduation, median_starting, latitude,
                        longitude]]

        # Append dataframe to csv file
        df = pd.DataFrame(school_data, columns=column_names)
        df.to_csv(csv_filename, mode="a", header=False)
        
        # Append college to list_completed
        list_completed.append(college)
        
        # Close the college's webpage
        driver.close()
        
        # Used for debugging
        print(list_completed)

https://www.usnews.com/best-colleges/princeton-university-2627 has already been processed
https://www.usnews.com/best-colleges/massachusetts-institute-of-technology-2178 has already been processed
https://www.usnews.com/best-colleges/harvard-university-2155 has already been processed
https://www.usnews.com/best-colleges/stanford-university-1305 has already been processed
https://www.usnews.com/best-colleges/yale-university-1426 has already been processed
https://www.usnews.com/best-colleges/university-of-pennsylvania-3378 has already been processed
https://www.usnews.com/best-colleges/california-institute-of-technology-1131 has already been processed
https://www.usnews.com/best-colleges/duke-university-2920 has already been processed
https://www.usnews.com/best-colleges/brown-university-3401 has already been processed
https://www.usnews.com/best-colleges/jhu-2077 has already been processed
https://www.usnews.com/best-colleges/northwestern-university-1739 has already been processed
https://www.usnews.com/best-colleges/columbia-university-2707 has already been processed
https://www.usnews.com/best-colleges/cornell-university-2711 has already been processed
https://www.usnews.com/best-colleges/university-of-chicago-1774 has already been processed
https://www.usnews.com/best-colleges/university-of-california-berkeley-1312 has already been processed
https://www.usnews.com/best-colleges/ucla-1315 has already been processed
https://www.usnews.com/best-colleges/rice-3604 has already been processed
https://www.usnews.com/best-colleges/dartmouth-college-2573 has already been processed
https://www.usnews.com/best-colleges/vanderbilt-3535 has already been processed
https://www.usnews.com/best-colleges/university-of-notre-dame-1840 has already been processed
https://www.usnews.com/best-colleges/university-of-michigan-ann-arbor-9092 has already been processed
https://www.usnews.com/best-colleges/georgetown-university-1445 has already been processed
https://www.usnews.com/best-colleges/unc-2974 has already been processed
https://www.usnews.com/best-colleges/carnegie-mellon-university-3242 has already been processed
https://www.usnews.com/best-colleges/emory-university-1564 has already been processed
https://www.usnews.com/best-colleges/uva-6968 has already been processed
https://www.usnews.com/best-colleges/washington-university-in-st-louis-2520 has already been processed
https://www.usnews.com/best-colleges/university-of-california-davis-1313 has already been processed
https://www.usnews.com/best-colleges/university-of-california-san-diego-1317 has already been processed
https://www.usnews.com/best-colleges/university-of-florida-1535 has already been processed
https://www.usnews.com/best-colleges/university-of-southern-california-1328 has already been processed
https://www.usnews.com/best-colleges/university-of-texas-at-austin-3658 has already been processed
https://www.usnews.com/best-colleges/georgia-institute-of-technology-1569 has already been processed
https://www.usnews.com/best-colleges/university-of-california-irvine-1314 has already been processed
https://www.usnews.com/best-colleges/nyu-2785 has already been processed
https://www.usnews.com/best-colleges/university-of-california-santa-barbara-1320 has already been processed
https://www.usnews.com/best-colleges/university-of-illinois-urbanachampaign-1775 has already been processed
https://www.usnews.com/best-colleges/university-of-wisconsin-3895 has already been processed
https://www.usnews.com/best-colleges/boston-college-2128 has already been processed
https://www.usnews.com/best-colleges/rutgers-new-brunswick-6964 has already been processed
https://www.usnews.com/best-colleges/tufts-university-2219 has already been processed
https://www.usnews.com/best-colleges/university-of-washington-3798 has already been processed
https://www.usnews.com/best-colleges/boston-university-2130 has already been processed
https://www.usnews.com/best-colleges/ohio-state-6883 has already been processed
https://www.usnews.com/best-colleges/purdue-university-west-lafayette-1825 has already been processed
https://www.usnews.com/best-colleges/university-of-maryland-2103 has already been processed
https://www.usnews.com/best-colleges/lehigh-university-3289 has already been processed
https://www.usnews.com/best-colleges/texas-am-university-college-station-10366 has already been processed
https://www.usnews.com/best-colleges/university-of-georgia-1598 has already been processed
https://www.usnews.com/best-colleges/university-of-rochester-2894 has already been processed
https://www.usnews.com/best-colleges/virginia-tech-3754 has already been processed
https://www.usnews.com/best-colleges/wake-forest-2978 has already been processed
https://www.usnews.com/best-colleges/case-western-reserve-university-3024 has already been processed
https://www.usnews.com/best-colleges/florida-state-university-1489 has already been processed
https://www.usnews.com/best-colleges/northeastern-university-2199 has already been processed
https://www.usnews.com/best-colleges/university-of-minnesota-twin-cities-3969 has already been processed
https://www.usnews.com/best-colleges/william-and-mary-3705 has already been processed
https://www.usnews.com/best-colleges/stony-brook-suny-2838 has already been processed
https://www.usnews.com/best-colleges/uconn-29013 has already been processed
https://www.usnews.com/best-colleges/brandeis-university-2133 has already been processed
https://www.usnews.com/best-colleges/michigan-state-2290 has already been processed
https://www.usnews.com/best-colleges/north-carolina-state-raleigh-2972 has already been processed
https://www.usnews.com/best-colleges/penn-state-6965 has already been processed
https://www.usnews.com/best-colleges/rpi-2803 has already been processed
https://www.usnews.com/best-colleges/santa-clara-university-1326 has already been processed
https://www.usnews.com/best-colleges/university-of-california-merced-4127 has already been processed
https://www.usnews.com/best-colleges/george-washington-university-1444 has already been processed
https://www.usnews.com/best-colleges/syracuse-university-2882 has already been processed
https://www.usnews.com/best-colleges/umass-amherst-2221 has already been processed
https://www.usnews.com/best-colleges/university-of-miami-1536 has already been processed
https://www.usnews.com/best-colleges/university-of-pittsburgh-3379 has already been processed
https://www.usnews.com/best-colleges/villanova-3388 has already been processed
https://www.usnews.com/best-colleges/suny-binghamton-2836 has already been processed
https://www.usnews.com/best-colleges/indiana-university-bloomington-1809 has already been processed
https://www.usnews.com/best-colleges/tulane-university-2029 has already been processed
https://www.usnews.com/best-colleges/colorado-school-of-mines-1348 has already been processed
https://www.usnews.com/best-colleges/pepperdine-university-1264 has already been processed
https://www.usnews.com/best-colleges/stevens-institute-of-technology-2639 has already been processed
https://www.usnews.com/best-colleges/ub-9554 has already been processed
https://www.usnews.com/best-colleges/university-of-california-riverside-1316 has already been processed
https://www.usnews.com/best-colleges/university-of-delaware-1431 has already been processed
https://www.usnews.com/best-colleges/rutgers-newark-2631 has already been processed
https://www.usnews.com/best-colleges/university-of-california-santa-cruz-1321 has already been processed
https://www.usnews.com/best-colleges/university-of-illinois-chicago-1776 has already been processed
https://www.usnews.com/best-colleges/wpi-2233 has already been processed
https://www.usnews.com/best-colleges/clemson-university-3425 has already been processed
https://www.usnews.com/best-colleges/marquette-university-3863 has already been processed
https://www.usnews.com/best-colleges/njit-2621 has already been processed
https://www.usnews.com/best-colleges/fordham-university-2722 has already been processed
https://www.usnews.com/best-colleges/smu-3613 has already been processed
https://www.usnews.com/best-colleges/temple-university-3371 has already been processed
https://www.usnews.com/best-colleges/university-of-south-florida-1537 has already been processed
https://www.usnews.com/best-colleges/auburn-university-1009 has already been processed
https://www.usnews.com/best-colleges/baylor-university-6967 has already been processed
https://www.usnews.com/best-colleges/gonzaga-university-3778 has already been processed
https://www.usnews.com/best-colleges/loyola-marymount-university-11649 has already been processed
https://www.usnews.com/best-colleges/university-of-iowa-1892 has already been processed
https://www.usnews.com/best-colleges/drexel-university-3256 has already been processed
https://www.usnews.com/best-colleges/illinois-institute-of-technology-1691 has already been processed
https://www.usnews.com/best-colleges/rit-2806 has already been processed
https://www.usnews.com/best-colleges/rutgers-university-camden-4741 has already been processed
https://www.usnews.com/best-colleges/tcu-3636 has already been processed
https://www.usnews.com/best-colleges/university-of-oregon-3223 has already been processed
https://www.usnews.com/best-colleges/university-of-san-diego-10395 has already been processed
https://www.usnews.com/best-colleges/american-university-1434 has already been processed
https://www.usnews.com/best-colleges/arizona-state-university-1081 has already been processed
https://www.usnews.com/best-colleges/california-state-university-long-beach-1139 has already been processed
https://www.usnews.com/best-colleges/cuny-city-college-2688 has already been processed
https://www.usnews.com/best-colleges/gmu-3749 has already been processed
https://www.usnews.com/best-colleges/saint-louis-university-2506 has already been processed
https://www.usnews.com/best-colleges/san-diego-state-university-1151 has already been processed
https://www.usnews.com/best-colleges/university-of-colorado-boulder-1370 has already been processed
https://www.usnews.com/best-colleges/university-of-tennessee-3530 has already been processed
https://www.usnews.com/best-colleges/yeshiva-university-2903 has already been processed
https://www.usnews.com/best-colleges/byu-3670 has already been processed
https://www.usnews.com/best-colleges/howard-university-1448 has already been processed
https://www.usnews.com/best-colleges/iowa-state-university-1869 has already been processed
https://www.usnews.com/best-colleges/suny-environmental-science-and-forestry-2851 has already been processed
https://www.usnews.com/best-colleges/university-of-arizona-1083 has already been processed
https://www.usnews.com/best-colleges/university-of-new-hampshire-2589 has already been processed
https://www.usnews.com/best-colleges/university-of-san-francisco-1325 has already been processed
https://www.usnews.com/best-colleges/the-university-of-texas-at-dallas-9741 has already been processed
https://www.usnews.com/best-colleges/university-of-utah-3675 has already been processed
https://www.usnews.com/best-colleges/creighton-university-2542 has already been processed
https://www.usnews.com/best-colleges/fairfield-university-1385 has already been processed
https://www.usnews.com/best-colleges/fiu-9635 has already been processed
https://www.usnews.com/best-colleges/james-madison-university-3721 has already been processed
https://www.usnews.com/best-colleges/ucf-3954 has already been processed
https://www.usnews.com/best-colleges/university-of-denver-1371 has already been processed
https://www.usnews.com/best-colleges/university-of-missouri-2516 has already been processed
https://www.usnews.com/best-colleges/university-of-oklahoma-3184 has already been processed
https://www.usnews.com/best-colleges/university-of-south-carolina-3448 has already been processed
https://www.usnews.com/best-colleges/california-state-university-fullerton-1137 has already been processed
https://www.usnews.com/best-colleges/chapman-university-1164 has already been processed
https://www.usnews.com/best-colleges/elon-university-2927 has already been processed
https://www.usnews.com/best-colleges/miami-university-7104 has already been processed
https://www.usnews.com/best-colleges/suny-albany-2835 has already been processed
https://www.usnews.com/best-colleges/university-of-dayton-3127 has already been processed
https://www.usnews.com/best-colleges/university-of-houston-3652 has already been processed
https://www.usnews.com/best-colleges/umbc-2105 has already been processed
https://www.usnews.com/best-colleges/university-of-vermont-3696 has already been processed
https://www.usnews.com/best-colleges/clarkson-university-2699 has already been processed
https://www.usnews.com/best-colleges/clark-university-massachusetts-2139 has already been processed
https://www.usnews.com/best-colleges/loyola-university-chicago-1710 has already been processed
https://www.usnews.com/best-colleges/oregon-state-3210 has already been processed
https://www.usnews.com/best-colleges/thomas-jefferson-university-12393 has already been processed
https://www.usnews.com/best-colleges/university-of-alabama-at-birmingham-1052 has already been processed
https://www.usnews.com/best-colleges/university-of-cincinnati-3125 has already been processed
https://www.usnews.com/best-colleges/university-of-the-pacific-1329 has already been processed
https://www.usnews.com/best-colleges/vcu-3735 has already been processed
https://www.usnews.com/best-colleges/colorado-state-university-1350 has already been processed
https://www.usnews.com/best-colleges/depaul-university-1671 has already been processed
https://www.usnews.com/best-colleges/duquesne-university-3258 has already been processed
https://www.usnews.com/best-colleges/michigan-tech-2292 has already been processed
https://www.usnews.com/best-colleges/seton-hall-university-new-jersey-2632 has already been processed
https://www.usnews.com/best-colleges/simmons-university-2208 has already been processed
https://www.usnews.com/best-colleges/university-of-kansas-1948 has already been processed
https://www.usnews.com/best-colleges/university-of-rhode-island-3414 has already been processed
https://www.usnews.com/best-colleges/stockton-university-9345 has already been processed
https://www.usnews.com/best-colleges/university-of-kentucky-1989 has already been processed
https://www.usnews.com/best-colleges/umass-lowell-2161 has already been processed
https://www.usnews.com/best-colleges/university-of-nebraska-2565 has already been processed
https://www.usnews.com/best-colleges/adelphi-university-2666 has already been processed
https://www.usnews.com/best-colleges/montclair-state-university-2617 has already been processed
https://www.usnews.com/best-colleges/rowan-university-2609 has already been processed
https://www.usnews.com/best-colleges/seattle-university-3790 has already been processed
https://www.usnews.com/best-colleges/st-johns-university-new-york-2823 has already been processed
https://www.usnews.com/best-colleges/university-of-mississippi-2440 has already been processed
https://www.usnews.com/best-colleges/university-of-st-thomas-minnesota-2345 has already been processed
https://www.usnews.com/best-colleges/california-state-university-san-bernardino-1142 has already been processed
https://www.usnews.com/best-colleges/florida-am-university-1480 has already been processed
https://www.usnews.com/best-colleges/kansas-state-university-1928 has already been processed
https://www.usnews.com/best-colleges/mercer-university-1580 has already been processed
https://www.usnews.com/best-colleges/quinnipiac-university-1402 has already been processed
https://www.usnews.com/best-colleges/university-of-alabama-1051 has already been processed
https://www.usnews.com/best-colleges/university-of-hawaii-manoa-1610 has already been processed
https://www.usnews.com/best-colleges/university-of-la-verne-1216 has already been processed
https://www.usnews.com/best-colleges/the-catholic-university-of-america-1437 has already been processed
https://www.usnews.com/best-colleges/drake-university-1860 has already been processed
https://www.usnews.com/best-colleges/ohio-university-3100 has already been processed
https://www.usnews.com/best-colleges/san-francisco-state-university-1154 has already been processed
https://www.usnews.com/best-colleges/university-of-arkansas-1108 has already been processed
https://www.usnews.com/best-colleges/university-of-north-carolina-charlotte-2975 has already been processed
https://www.usnews.com/best-colleges/washington-state-3800 has already been processed
https://www.usnews.com/best-colleges/bradley-university-1641 has already been processed
https://www.usnews.com/best-colleges/california-state-university-fresno-1147 has already been processed
https://www.usnews.com/best-colleges/hofstra-university-2732 has already been processed
https://www.usnews.com/best-colleges/louisiana-state-university-baton-rouge-2010 has already been processed
https://www.usnews.com/best-colleges/missouri-university-of-science-and-technology-2517 has already been processed
https://www.usnews.com/best-colleges/oklahoma-state-3170 has already been processed
https://www.usnews.com/best-colleges/samford-university-1036 has already been processed
https://www.usnews.com/best-colleges/st-john-fisher-university-2821 has already been processed
https://www.usnews.com/best-colleges/university-of-detroit-mercy-2323 has already been processed
https://www.usnews.com/best-colleges/university-of-idaho-1626 has already been processed
https://www.usnews.com/best-colleges/east-carolina-university-2923 has already been processed
https://www.usnews.com/best-colleges/the-sage-colleges-2810 has already been processed
https://www.usnews.com/best-colleges/touro-university-10142 has already been processed
https://www.usnews.com/best-colleges/university-of-louisville-1999 has already been processed
https://www.usnews.com/best-colleges/university-of-nevada-2568 has already been processed
https://www.usnews.com/best-colleges/university-of-tulsa-3185 has already been processed
https://www.usnews.com/best-colleges/indiana-universitypurdue-university-indianapolis-1813 has already been processed
https://www.usnews.com/best-colleges/la-salle-university-3287 has already been processed
https://www.usnews.com/best-colleges/the-new-school-20662 has already been processed
https://www.usnews.com/best-colleges/robert-morris-university-pennsylvania-3359 has already been processed
https://www.usnews.com/best-colleges/university-of-north-carolina-wilmington-2984 has already been processed
https://www.usnews.com/best-colleges/valparaiso-university-1842 has already been processed
https://www.usnews.com/best-colleges/wayne-state-2329 has already been processed
https://www.usnews.com/best-colleges/xavier-university-3144 has already been processed
https://www.usnews.com/best-colleges/chatham-university-3244 has already been processed
https://www.usnews.com/best-colleges/florida-atlantic-university-1481 has already been processed
https://www.usnews.com/best-colleges/illinois-state-university-1692 has already been processed
https://www.usnews.com/best-colleges/pacific-university-3212 has already been processed
https://www.usnews.com/best-colleges/sacred-heart-university-1403 has already been processed
https://www.usnews.com/best-colleges/umass-dartmouth-2210 has already been processed
https://www.usnews.com/best-colleges/west-chester-3328 has already been processed
https://www.usnews.com/best-colleges/ball-state-university-1786 has already been processed
https://www.usnews.com/best-colleges/the-college-of-st-scholastica-2343 has already been processed
https://www.usnews.com/best-colleges/mississippi-state-2423 has already been processed
https://www.usnews.com/best-colleges/springfield-college-2211 has already been processed

ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

# Additional code used to analyze tags

In [15]:
for t in text:
    print(t)

<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">$65,524</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">8,832</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">4%</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">1470-1570</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">34-35</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">$65,524</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">$65,524</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">12</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">71</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">27</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">59,822</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">19:1</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">24,944</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">33,776</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">8,161</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">88%</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">88%</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>
<p class="Paragraph-sc-1iyax29-0 kqzCwD">N/A</p>

# Jupyter Data Analysis

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('DSCI_105_Final_Dataset.csv')
df

,Unnamed: 0,School,School_Rank,School_Type,Setting,Address,City,State,Private_Cost,In_State_Cost,...,Ethnic_Group_7,Ethnic_Percentage_7,Ethnic_Group_8,Ethnic_Percentage_8,Graduation_Rate,Percentage_of_Graduating_Students_Who_Borrowed,Average_Debt_at_Graduation,Median_Starting_Salary,Latitude,Longitude
0,0,Princeton University,1,Private,Suburban,"Princeton, NJ, 08544",Princeton,NJ,59710.0,NaN,...,Two or more races,7.0,Unknown,2,88,17.0,12500.0,64287.0,40.3492,-74.6528
1,0,Massachusetts Institute of Technology,2,Private,Urban,"77 Massachusetts Avenue, Cambridge, MA, 02139",Cambridge,MA,60156.0,NaN,...,Two or more races,7.0,Unknown,3,89,15.0,25556.0,102988.0,42.3647,-71.1042
2,0,Harvard University,3,Private,NaN,"Cambridge, MA, 02138",Cambridge,MA,59076.0,NaN,...,Two or more races,8.0,Unknown,1,87,15.0,13683.0,86549.0,42.3770,-71.1256
3,0,Stanford University,3,Private,Suburban,"Stanford, CA, 94305",Stanford,CA,62484.0,NaN,...,Black,7.0,American Indian,1,73,14.0,20691.0,77677.0,37.4236,-122.1619
4,0,Yale University,5,Private,City,"New Haven, CT, 06520",New Haven,CT,64700.0,NaN,...,Two or more races,7.0,Unknown,1,88,14.0,17910.0,60511.0,41.3082,-72.9282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,0,University of St. Francis,280,Private,Suburban,"500 Wilcox Street, Joliet, IL, 60435",Joliet,IL,37000.0,NaN,...,International,3.0,Unknown,1,47,72.0,35927.0,57402.0,41.5454,-88.1299
293,0,University of Texas at San Antonio,280,Public,Urban,"One UTSA Circle, San Antonio, TX, 78249",San Antonio,TX,NaN,10580.0,...,International,1.0,Unknown,1,32,60.0,21963.0,38500.0,29.5612,-98.6117
294,0,University of Toledo,280,Public,Urban,"2801 W. Bancroft, Toledo, OH, 43606",Toledo,OH,NaN,11920.0,...,Asian,3.0,Unknown,3,33,75.0,24744.0,46234.0,41.6712,-83.6060
295,0,Alvernia University,296,Private,City,"400 St. Bernardine Street, Reading, PA, 19607",Reading,PA,42810.0,NaN,...,Unknown,3.0,Asian,2,44,NaN,NaN,49633.0,40.2995,-75.9876
296,0,Edgewood College,296,Private,NaN,"1000 Edgewood College Drive, Madison, WI, 53711",Madison,WI,33550.0,NaN,...,Unknown,2.0,International,1,42,NaN,NaN,52280.0,43.0356,-89.4526

In [3]:
# Drop columns that had large amounts of NA's
df = df.drop(['Unnamed: 0', 'Ethnic_Group_7', 'Ethnic_Percentage_7', 'Ethnic_Group_8', 'Ethnic_Percentage_8'], axis=1)
df

,School,School_Rank,School_Type,Setting,Address,City,State,Private_Cost,In_State_Cost,Out_State_Cost,...,Ethnic_Group_5,Ethnic_Percentage_5,Ethnic_Group_6,Ethnic_Percentage_6,Graduation_Rate,Percentage_of_Graduating_Students_Who_Borrowed,Average_Debt_at_Graduation,Median_Starting_Salary,Latitude,Longitude
0,Princeton University,1,Private,Suburban,"Princeton, NJ, 08544",Princeton,NJ,59710.0,NaN,NaN,...,Hispanic,10.0,Black,8.0,88,17.0,12500.0,64287.0,40.3492,-74.6528
1,Massachusetts Institute of Technology,2,Private,Urban,"77 Massachusetts Avenue, Cambridge, MA, 02139",Cambridge,MA,60156.0,NaN,NaN,...,International,11.0,Black,8.0,89,15.0,25556.0,102988.0,42.3647,-71.1042
2,Harvard University,3,Private,NaN,"Cambridge, MA, 02138",Cambridge,MA,59076.0,NaN,NaN,...,Hispanic,12.0,Black,9.0,87,15.0,13683.0,86549.0,42.3770,-71.1256
3,Stanford University,3,Private,Suburban,"Stanford, CA, 94305",Stanford,CA,62484.0,NaN,NaN,...,International,11.0,Two or more races,10.0,73,14.0,20691.0,77677.0,37.4236,-122.1619
4,Yale University,5,Private,City,"New Haven, CT, 06520",New Haven,CT,64700.0,NaN,NaN,...,International,10.0,Black,8.0,88,14.0,17910.0,60511.0,41.3082,-72.9282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,University of St. Francis,280,Private,Suburban,"500 Wilcox Street, Joliet, IL, 60435",Joliet,IL,37000.0,NaN,NaN,...,White,4.0,American Indian,3.0,47,72.0,35927.0,57402.0,41.5454,-88.1299
293,University of Texas at San Antonio,280,Public,Urban,"One UTSA Circle, San Antonio, TX, 78249",San Antonio,TX,NaN,10580.0,26798.0,...,Asian,6.0,Two or more races,3.0,32,60.0,21963.0,38500.0,29.5612,-98.6117
294,University of Toledo,280,Public,Urban,"2801 W. Bancroft, Toledo, OH, 43606",Toledo,OH,NaN,11920.0,21280.0,...,Hispanic,6.0,Two or more races,4.0,33,75.0,24744.0,46234.0,41.6712,-83.6060
295,Alvernia University,296,Private,City,"400 St. Bernardine Street, Reading, PA, 19607",Reading,PA,42810.0,NaN,NaN,...,International,4.0,Two or more races,3.0,44,NaN,NaN,49633.0,40.2995,-75.9876
296,Edgewood College,296,Private,NaN,"1000 Edgewood College Drive, Madison, WI, 53711",Madison,WI,33550.0,NaN,NaN,...,Asian,3.0,Two or more races,3.0,42,NaN,NaN,52280.0,43.0356,-89.4526

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 47 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   School                                          297 non-null    object
 1   School_Rank                                     297 non-null    int64
 2   School_Type                                     297 non-null    object
 3   Setting                                         221 non-null    object
 4   Address                                         297 non-null    object
 5   City                                            297 non-null    object
 6   State                                           297 non-null    object
 7   Private_Cost                                    139 non-null    float64
 8   In_State_Cost                                   158 non-null    float64
 9   Out_State_Cost                                  158 non-null    float64
 10  Average_Cost_After_Aid                          297 non-null    int64
 11  Undergraduate_Enrollment                        297 non-null    int64
 12  Acceptance_Rate                                 297 non-null    int64
 13  Application_Date                                294 non-null    object
 14  SAT_Lower                                       263 non-null    float64
 15  SAT_Upper                                       263 non-null    float64
 16  ACT_Lower                                       264 non-null    float64
 17  ACT_Upper                                       264 non-null    float64
 18  High_School_GPA                                 233 non-null    float64
 19  Room_and_Board                                  295 non-null    float64
 20  Average_Need_Based_Aid_Package                  282 non-null    float64
 21  Bibliometric_rank                               297 non-null    int64
 22  Graduate_Enrollment                             297 non-null    int64
 23  Total_Enrollment                                297 non-null    int64
 24  Full_Time_Students                              297 non-null    int64
 25  Student_Faculty_Ratio                           297 non-null    int64
 26  Classes_Under20_Students                        287 non-null    float64
 27  Male_Student_Percentage                         297 non-null    int64
 28  Female_Student_Percentage                       297 non-null    int64
 29  Minority_Enrollment                             297 non-null    object
 30  Minority_Percentage                             297 non-null    int64
 31  Ethnic_Group_2                                  297 non-null    object
 32  Ethnic_Percentage_2                             297 non-null    int64
 33  Ethnic_Group_3                                  297 non-null    object
 34  Ethnic_Percentage_3                             297 non-null    int64
 35  Ethnic_Group_4                                  297 non-null    object
 36  Ethnic_Percentage_4                             297 non-null    int64
 37  Ethnic_Group_5                                  295 non-null    object
 38  Ethnic_Percentage_5                             295 non-null    float64
 39  Ethnic_Group_6                                  292 non-null    object
 40  Ethnic_Percentage_6                             292 non-null    float64
 41  Graduation_Rate                                 297 non-null    int64
 42  Percentage_of_Graduating_Students_Who_Borrowed  277 non-null    float64
 43  Average_Debt_at_Graduation                      277 non-null    float64
 44  Median_Starting_Salary                          295 non-null    float64
 45  Latitude                                        297 non-null    float64
 46  Longitude                                       297 non-null    float64
dtypes: float64(18), int64(16), object(13)
memory usage: 109.2+ KB

In [5]:
df['Setting'].describe()

count       221
unique        4
top       Urban
freq         82
Name: Setting, dtype: object

In [6]:
df['State'].describe()

count     297
unique     49
top        CA
freq       29
Name: State, dtype: object

In [7]:
df['Private_Cost'].describe()

count      139.000000
mean     50846.381295
std      12111.342344
min       6496.000000
25%      42440.000000
50%      51763.000000
75%      61725.500000
max      68237.000000
Name: Private_Cost, dtype: float64

In [8]:
df['In_State_Cost'].describe()

count      158.000000
mean     12351.094937
std       3785.975868
min       4532.000000
25%       9784.250000
50%      12118.500000
75%      14874.250000
max      25041.000000
Name: In_State_Cost, dtype: float64

In [9]:
df['Out_State_Cost'].describe()

count      158.000000
mean     30364.291139
std       9472.404289
min       8532.000000
25%      23102.000000
50%      29483.000000
75%      36324.000000
max      58950.000000
Name: Out_State_Cost, dtype: float64

In [10]:
df['Minority_Percentage'].describe()

count    297.000000
mean      40.175084
std       19.861080
min        1.000000
25%       24.000000
50%       38.000000
75%       52.000000
max       97.000000
Name: Minority_Percentage, dtype: float64

In [11]:
df['Ethnic_Group_2'].describe()

count       297
unique        5
top       White
freq        246
Name: Ethnic_Group_2, dtype: object

In [12]:
## Correlations between variables
print("Correlation between School_Rank and Acceptance_Rate: " + str(np.corrcoef(df['School_Rank'], df['Acceptance_Rate'])[0][1]))
print("Correlation between School_Rank and Graduation_Rate: " + str(np.corrcoef(df['School_Rank'], df['Graduation_Rate'])[0][1]))
print("Correlation between Acceptance_Rate and Graduation_Rate: " + str(np.corrcoef(df['Acceptance_Rate'], df['Graduation_Rate'])[0][1]))

Correlation between School_Rank and Acceptance_Rate: 0.7294698880940215
Correlation between School_Rank and Graduation_Rate: -0.6845708848311595
Correlation between Acceptance_Rate and Graduation_Rate: -0.6353400317295342

In [13]:
df_private = df[df['School_Type'] == 'Private']
df_private

,School,School_Rank,School_Type,Setting,Address,City,State,Private_Cost,In_State_Cost,Out_State_Cost,...,Ethnic_Group_5,Ethnic_Percentage_5,Ethnic_Group_6,Ethnic_Percentage_6,Graduation_Rate,Percentage_of_Graduating_Students_Who_Borrowed,Average_Debt_at_Graduation,Median_Starting_Salary,Latitude,Longitude
0,Princeton University,1,Private,Suburban,"Princeton, NJ, 08544",Princeton,NJ,59710.0,NaN,NaN,...,Hispanic,10.0,Black,8.0,88,17.0,12500.0,64287.0,40.3492,-74.6528
1,Massachusetts Institute of Technology,2,Private,Urban,"77 Massachusetts Avenue, Cambridge, MA, 02139",Cambridge,MA,60156.0,NaN,NaN,...,International,11.0,Black,8.0,89,15.0,25556.0,102988.0,42.3647,-71.1042
2,Harvard University,3,Private,NaN,"Cambridge, MA, 02138",Cambridge,MA,59076.0,NaN,NaN,...,Hispanic,12.0,Black,9.0,87,15.0,13683.0,86549.0,42.3770,-71.1256
3,Stanford University,3,Private,Suburban,"Stanford, CA, 94305",Stanford,CA,62484.0,NaN,NaN,...,International,11.0,Two or more races,10.0,73,14.0,20691.0,77677.0,37.4236,-122.1619
4,Yale University,5,Private,City,"New Haven, CT, 06520",New Haven,CT,64700.0,NaN,NaN,...,International,10.0,Black,8.0,88,14.0,17910.0,60511.0,41.3082,-72.9282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Marian University (IN),280,Private,City,"3200 Cold Spring Road, Indianapolis, IN, 46222",Indianapolis,IN,39100.0,NaN,NaN,...,Two or more races,5.0,Asian,3.0,42,70.0,33974.0,54162.0,39.7890,-86.2136
287,Oklahoma City University,280,Private,Urban,"2501 N. Blackwelder, Oklahoma City, OK, 73106",Oklahoma City,OK,33586.0,NaN,NaN,...,Black,5.0,International,5.0,60,55.0,27664.0,46103.0,35.4853,-97.5372
292,University of St. Francis,280,Private,Suburban,"500 Wilcox Street, Joliet, IL, 60435",Joliet,IL,37000.0,NaN,NaN,...,White,4.0,American Indian,3.0,47,72.0,35927.0,57402.0,41.5454,-88.1299
295,Alvernia University,296,Private,City,"400 St. Bernardine Street, Reading, PA, 19607",Reading,PA,42810.0,NaN,NaN,...,International,4.0,Two or more races,3.0,44,NaN,NaN,49633.0,40.2995,-75.9876
296,Edgewood College,296,Private,NaN,"1000 Edgewood College Drive, Madison, WI, 53711",Madison,WI,33550.0,NaN,NaN,...,Asian,3.0,Two or more races,3.0,42,NaN,NaN,52280.0,43.0356,-89.4526

In [14]:
df_public = df[df['School_Type'] == 'Public']
df_public

,School,School_Rank,School_Type,Setting,Address,City,State,Private_Cost,In_State_Cost,Out_State_Cost,...,Ethnic_Group_5,Ethnic_Percentage_5,Ethnic_Group_6,Ethnic_Percentage_6,Graduation_Rate,Percentage_of_Graduating_Students_Who_Borrowed,Average_Debt_at_Graduation,Median_Starting_Salary,Latitude,Longitude
14,"University of California, Berkeley",15,Public,City,"110 Sproul Hall, Berkeley, CA, 94720",Berkeley,CA,NaN,15891.0,48465.0,...,International,13.0,Two or more races,6.0,82,28.0,16419.0,54348.0,37.8738,-122.2549
15,"University of California, Los Angeles",15,Public,Urban,"405 Hilgard Avenue, Los Angeles, CA, 90095",Los Angeles,CA,NaN,13752.0,46326.0,...,International,9.0,Two or more races,7.0,84,33.0,17920.0,39803.0,33.7866,-118.2987
20,University of Michigan--Ann Arbor,21,Public,City,"500 S. State St., Ann Arbor, MI, 48109",Ann Arbor,MI,NaN,17786.0,57273.0,...,International,8.0,Two or more races,5.0,81,35.0,28487.0,59818.0,42.2776,-83.7409
22,University of North Carolina at Chapel Hill,22,Public,NaN,"311 Henry Owl Building, CB#3350, Chapel Hill, ...",Chapel Hill,NC,NaN,8998.0,39338.0,...,Black,8.0,Two or more races,5.0,85,33.0,20680.0,46617.0,36.0525,-79.1077
25,University of Virginia,24,Public,NaN,"Charlottesville, VA, 22904",Charlottesville,VA,NaN,22323.0,58950.0,...,Hispanic,7.0,Two or more races,6.0,91,33.0,26211.0,58760.0,38.0401,-78.4851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,Portland State University,280,Public,Urban,"PO Box 751, Portland, OR, 97207",Portland,OR,NaN,9375.0,24495.0,...,Two or more races,7.0,Black,5.0,32,50.0,22621.0,37970.0,45.5235,-122.6762
290,Southern Illinois University--Carbondale,280,Public,Rural,"Undergraduate Admissions, 1263 Lincoln Drive, ...",Carbondale,IL,NaN,15522.0,15522.0,...,Two or more races,4.0,Asian,2.0,35,62.0,28811.0,40092.0,37.7200,-89.2158
291,Texas State University,280,Public,Suburban,"601 University Drive, San Marcos, TX, 78666",San Marcos,TX,NaN,12207.0,24447.0,...,Two or more races,4.0,Asian,3.0,35,63.0,24875.0,39578.0,29.8754,-97.9404
293,University of Texas at San Antonio,280,Public,Urban,"One UTSA Circle, San Antonio, TX, 78249",San Antonio,TX,NaN,10580.0,26798.0,...,Asian,6.0,Two or more races,3.0,32,60.0,21963.0,38500.0,29.5612,-98.6117
294,University of Toledo,280,Public,Urban,"2801 W. Bancroft, Toledo, OH, 43606",Toledo,OH,NaN,11920.0,21280.0,...,Hispanic,6.0,Two or more races,4.0,33,75.0,24744.0,46234.0,41.6712,-83.6060

# Tableau Stories for Dashboards

#### Umass vs Clark Dashboard
A student that wants to review whether they should attend Clark University or UMASS - Amherst. They are able to investigate the school size, diversity, average debt at graduation and average cost after aid. Finally, the most important  factor, the student can see the median starting salary for alumni from each school.

#### Global Dashboard
The global dashboard was insight to researchers, not necessarily a prospective student. We were able to find trends between variables, plot out school locations, see best schools for income after graduation, along with seeing trends in the school setting (urban, city, rural, suburban).

# Project Report

### Methods

   Using the selenium package, we went through each university link from the usnews top national universities (US). Selenium would gather the entire pages html, which we then used to scrape data from. Our biggest issue was the styling of the pages. USnews requires users to scroll towards the bottom of the page for more of it to load, this is why Selenium was vital to the project as it was able to bypass this feature and get the whole script. 
   
  Web scraping was broken into two sections. A heavy portion was in one class, and we used an indexing approach to gather the data. However, the remaining were in their own classes. Both situations took advantage of varying string manipulations, such as ‘.text’, ‘.replace’, and ‘.strip’. We did come across an issue with public schools. Since Selenium was slow, we had been using a sample test list. This test list was only private schools. Once we realized that public schools also had ’in-state’ and ‘out-of-state’ tuition, we had to adjust our code to include this.
  
  Some data manipulation was the adding of longitude and latitude coordinates via the geocode package. We separated each school address and using only the zipcode, geocode was able to return the longitude and latitude of the location. This allowed for mapping opportunities in Tableau. We utilized ‘if-else’ statements to leave objects blank when there was no data for a specific school. This allowed us to use Tableau’s remove NA feature during analysis. This was crucial for the ethnicity rankings per school. Many schools near the bottom of the list only had a few ethnicity groups, rather than seven (the average). There were also a lot of testing code along the way to ensure the code is running properly, such as checking if the university was already completed or not.

### Findings:

Our findings helped give a broad picture to the best schools in the US. We were able to look into the best and worst of many factors, such as, acceptance rate, SAT/ACT scores, tuition, costs after financial aid, schools per state, and more.

Specifically, University of South Dakota had a 99% acceptance rate. California Institute of Technology and Harvard both had the lowest acceptance rate at 3%. Schools were pretty evenly split between public and private schools, with 158 public and 139 private. We found a spatial pattern, the US seems to be split down the middle with most schools scattered on the eastern half. This is likely due to population spacing, there are too many people living in the Dakotas. 

We think that this is a useful project because it helps bring visuals and straightforward answers to high school students looking into higher education. Going through sites such as niche, USnews, PrincetonReview, etc. can be very challenging. It typically leads to a student opening 50 tabs and trying to remember which school had the best earnings after graduation, or writing down notes to compare by hand, both of which are not ideal. Our code breaks this difficulty down, allowing students to filter a list of their chosen schools and analyze every factor that the USnews site has to offer, except a few. For instance, a future addition to this project could be adding the schools best majors, adding more of the bibliometric/research stats, and the short bio on dorm options. A huge addition could also be taking the top 300 schools from several different ranking sites (PrincetonReview, Niche, Forbes). Another cool option would be putting this into our own website, after checking the legality of that of course.

### Implications of analysis:

There are a few things that must be considered when reviewing our analysis. Most importantly, all of our data comes from USnews. As many people know, there are several sites that rank schools and each has their own ranking system. Each list is biased for many reasons, but ours is entirely biased to USnews' ranking system. Besides only getting USnews data. The data may not be entirely accurate. The list is updated to 2024, but we don’t know if each schools’ inputs are. For instance, some schools were missing average SAT scores and high school GPAs, but it is possible that we could find this information on other sites. Missing data also made it difficult to compare some of the schools on the list.